// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package marketplaceproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	ShopID               int32    `protobuf:"varint,2,opt,name=ShopID,json=shopID,proto3" json:"ShopID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=Quantity,json=quantity,proto3" json:"Quantity,omitempty"`
	PricePerKG           int32    `protobuf:"varint,5,opt,name=PricePerKG,json=pricePerKG,proto3" json:"PricePerKG,omitempty"`
	StockKG              float32  `protobuf:"fixed32,6,opt,name=StockKG,json=stockKG,proto3" json:"StockKG,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=CreatedAt,json=createdAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=UpdatedAt,json=updatedAt,proto3" json:"UpdatedAt,omitempty"`
	Slug                 string   `protobuf:"bytes,9,opt,name=Slug,json=slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_fb0b2a34a820b239, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Product) GetShopID() int32 {
	if m != nil {
		return m.ShopID
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetPricePerKG() int32 {
	if m != nil {
		return m.PricePerKG
	}
	return 0
}

func (m *Product) GetStockKG() float32 {
	if m != nil {
		return m.StockKG
	}
	return 0
}

func (m *Product) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Product) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Product) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type ListProductsReq struct {
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListProductsReq) Reset()         { *m = ListProductsReq{} }
func (m *ListProductsReq) String() string { return proto.CompactTextString(m) }
func (*ListProductsReq) ProtoMessage()    {}
func (*ListProductsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_fb0b2a34a820b239, []int{1}
}
func (m *ListProductsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsReq.Unmarshal(m, b)
}
func (m *ListProductsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsReq.Marshal(b, m, deterministic)
}
func (dst *ListProductsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsReq.Merge(dst, src)
}
func (m *ListProductsReq) XXX_Size() int {
	return xxx_messageInfo_ListProductsReq.Size(m)
}
func (m *ListProductsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsReq proto.InternalMessageInfo

func (m *ListProductsReq) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ListProductsResp struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=Products,json=products,proto3" json:"Products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProductsResp) Reset()         { *m = ListProductsResp{} }
func (m *ListProductsResp) String() string { return proto.CompactTextString(m) }
func (*ListProductsResp) ProtoMessage()    {}
func (*ListProductsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_fb0b2a34a820b239, []int{2}
}
func (m *ListProductsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsResp.Unmarshal(m, b)
}
func (m *ListProductsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsResp.Marshal(b, m, deterministic)
}
func (dst *ListProductsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsResp.Merge(dst, src)
}
func (m *ListProductsResp) XXX_Size() int {
	return xxx_messageInfo_ListProductsResp.Size(m)
}
func (m *ListProductsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsResp proto.InternalMessageInfo

func (m *ListProductsResp) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type GetProductByIDReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductByIDReq) Reset()         { *m = GetProductByIDReq{} }
func (m *GetProductByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetProductByIDReq) ProtoMessage()    {}
func (*GetProductByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_fb0b2a34a820b239, []int{3}
}
func (m *GetProductByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductByIDReq.Unmarshal(m, b)
}
func (m *GetProductByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductByIDReq.Marshal(b, m, deterministic)
}
func (dst *GetProductByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductByIDReq.Merge(dst, src)
}
func (m *GetProductByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetProductByIDReq.Size(m)
}
func (m *GetProductByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductByIDReq proto.InternalMessageInfo

func (m *GetProductByIDReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetProductBySlugReq struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductBySlugReq) Reset()         { *m = GetProductBySlugReq{} }
func (m *GetProductBySlugReq) String() string { return proto.CompactTextString(m) }
func (*GetProductBySlugReq) ProtoMessage()    {}
func (*GetProductBySlugReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_fb0b2a34a820b239, []int{4}
}
func (m *GetProductBySlugReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductBySlugReq.Unmarshal(m, b)
}
func (m *GetProductBySlugReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductBySlugReq.Marshal(b, m, deterministic)
}
func (dst *GetProductBySlugReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductBySlugReq.Merge(dst, src)
}
func (m *GetProductBySlugReq) XXX_Size() int {
	return xxx_messageInfo_GetProductBySlugReq.Size(m)
}
func (m *GetProductBySlugReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductBySlugReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductBySlugReq proto.InternalMessageInfo

func (m *GetProductBySlugReq) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "marketplaceproto.Product")
	proto.RegisterType((*ListProductsReq)(nil), "marketplaceproto.ListProductsReq")
	proto.RegisterType((*ListProductsResp)(nil), "marketplaceproto.ListProductsResp")
	proto.RegisterType((*GetProductByIDReq)(nil), "marketplaceproto.GetProductByIDReq")
	proto.RegisterType((*GetProductBySlugReq)(nil), "marketplaceproto.GetProductBySlugReq")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_product_fb0b2a34a820b239) }

var fileDescriptor_product_fb0b2a34a820b239 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x4f, 0xc2, 0x30,
	0x14, 0xc5, 0xd3, 0x01, 0xfb, 0x73, 0x89, 0x8a, 0x35, 0x31, 0x95, 0x10, 0xb3, 0xcc, 0x97, 0xf9,
	0xc2, 0x03, 0xc6, 0x37, 0x5f, 0xd4, 0x25, 0x64, 0xc1, 0xe8, 0x2c, 0xf1, 0x03, 0x94, 0xd1, 0xe0,
	0x02, 0x6c, 0x65, 0xed, 0x1e, 0xf8, 0xcc, 0x7e, 0x09, 0xb3, 0x76, 0x23, 0x48, 0x7c, 0x3c, 0xe7,
	0xfc, 0x72, 0x7b, 0x4f, 0x2f, 0x9c, 0x89, 0xb2, 0x58, 0x56, 0xa9, 0x1a, 0x8b, 0xb2, 0x50, 0x05,
	0x1e, 0x6c, 0x59, 0xb9, 0xe6, 0x4a, 0x6c, 0x58, 0xca, 0xb5, 0x33, 0x84, 0x05, 0x93, 0xdc, 0xa4,
	0xc1, 0x0f, 0x02, 0x27, 0x31, 0x3c, 0x3e, 0x07, 0x2b, 0x8e, 0x08, 0xf2, 0x51, 0xd8, 0xa3, 0x56,
	0x16, 0xe1, 0x6b, 0xb0, 0xe7, 0xdf, 0x85, 0x88, 0x23, 0x62, 0x69, 0xcf, 0x96, 0x5a, 0x61, 0x0c,
	0xdd, 0x77, 0xb6, 0xe5, 0xa4, 0xe3, 0xa3, 0xd0, 0xa3, 0xdd, 0x9c, 0x6d, 0x39, 0x1e, 0x82, 0xfb,
	0x59, 0xb1, 0x5c, 0x65, 0x6a, 0x4f, 0xba, 0x9a, 0x76, 0x77, 0x8d, 0xc6, 0xb7, 0x00, 0x49, 0x99,
	0xa5, 0x3c, 0xe1, 0xe5, 0x6c, 0x4a, 0x7a, 0x3a, 0x05, 0x71, 0x70, 0x30, 0x01, 0x67, 0xae, 0x8a,
	0x74, 0x3d, 0x9b, 0x12, 0xdb, 0x47, 0xa1, 0x45, 0x1d, 0x69, 0x24, 0x1e, 0x81, 0xf7, 0x5a, 0x72,
	0xa6, 0xf8, 0xf2, 0x59, 0x11, 0xc7, 0x47, 0x61, 0x87, 0x7a, 0x69, 0x6b, 0xd4, 0xe9, 0x97, 0x58,
	0x36, 0xa9, 0x6b, 0xd2, 0xaa, 0x35, 0xea, 0x2d, 0xe7, 0x9b, 0x6a, 0x45, 0x3c, 0xb3, 0xa5, 0xdc,
	0x54, 0xab, 0xe0, 0x03, 0x2e, 0xde, 0x32, 0xa9, 0x9a, 0xc2, 0x92, 0xf2, 0x1d, 0x7e, 0x02, 0x10,
	0x6c, 0x95, 0xe5, 0x4c, 0x65, 0x45, 0xae, 0x8b, 0xf6, 0x27, 0xa3, 0xf1, 0xe9, 0x9f, 0x8d, 0x93,
	0x03, 0x43, 0x8f, 0xf8, 0x20, 0x86, 0xc1, 0xdf, 0x81, 0x52, 0xe0, 0x47, 0x70, 0x5b, 0x4d, 0x90,
	0xdf, 0x09, 0xfb, 0x93, 0x9b, 0x7f, 0xe6, 0x19, 0x82, 0xba, 0xcd, 0xb1, 0x64, 0x70, 0x07, 0x97,
	0x53, 0xde, 0x4e, 0x7a, 0xd9, 0xc7, 0x51, 0xbd, 0xdd, 0xc9, 0x49, 0x82, 0x7b, 0xb8, 0x3a, 0x86,
	0xea, 0x82, 0x35, 0x86, 0x41, 0xf7, 0xd3, 0x60, 0xd3, 0x75, 0x61, 0xeb, 0x87, 0x1e, 0x7e, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x45, 0x06, 0x1b, 0xf0, 0x0f, 0x02, 0x00, 0x00,
}
