// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package authproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginReq struct {
	UsernameOrEmail      string   `protobuf:"bytes,1,opt,name=username_or_email,json=usernameOrEmail,proto3" json:"username_or_email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_4de06fe703aa931b, []int{0}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsernameOrEmail() string {
	if m != nil {
		return m.UsernameOrEmail
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_4de06fe703aa931b, []int{1}
}
func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (dst *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(dst, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Type                 int32    `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	FullName             string   `protobuf:"bytes,7,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_4de06fe703aa931b, []int{2}
}
func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (dst *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(dst, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegisterReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RegisterReq) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type RegisterResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_4de06fe703aa931b, []int{3}
}
func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (dst *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(dst, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RefreshTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenReq) Reset()         { *m = RefreshTokenReq{} }
func (m *RefreshTokenReq) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenReq) ProtoMessage()    {}
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_4de06fe703aa931b, []int{4}
}
func (m *RefreshTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenReq.Unmarshal(m, b)
}
func (m *RefreshTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenReq.Marshal(b, m, deterministic)
}
func (dst *RefreshTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenReq.Merge(dst, src)
}
func (m *RefreshTokenReq) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenReq.Size(m)
}
func (m *RefreshTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenReq proto.InternalMessageInfo

func (m *RefreshTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshTokenResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenResp) Reset()         { *m = RefreshTokenResp{} }
func (m *RefreshTokenResp) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResp) ProtoMessage()    {}
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_4de06fe703aa931b, []int{5}
}
func (m *RefreshTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResp.Unmarshal(m, b)
}
func (m *RefreshTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResp.Marshal(b, m, deterministic)
}
func (dst *RefreshTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResp.Merge(dst, src)
}
func (m *RefreshTokenResp) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResp.Size(m)
}
func (m *RefreshTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResp proto.InternalMessageInfo

func (m *RefreshTokenResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "authproto.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "authproto.LoginResp")
	proto.RegisterType((*RegisterReq)(nil), "authproto.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "authproto.RegisterResp")
	proto.RegisterType((*RefreshTokenReq)(nil), "authproto.RefreshTokenReq")
	proto.RegisterType((*RefreshTokenResp)(nil), "authproto.RefreshTokenResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MarketplaceAuthClient is the client API for MarketplaceAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketplaceAuthClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
}

type marketplaceAuthClient struct {
	cc *grpc.ClientConn
}

func NewMarketplaceAuthClient(cc *grpc.ClientConn) MarketplaceAuthClient {
	return &marketplaceAuthClient{cc}
}

func (c *marketplaceAuthClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	out := new(RefreshTokenResp)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketplaceAuthServer is the server API for MarketplaceAuth service.
type MarketplaceAuthServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenResp, error)
}

func RegisterMarketplaceAuthServer(s *grpc.Server, srv MarketplaceAuthServer) {
	s.RegisterService(&_MarketplaceAuth_serviceDesc, srv)
}

func _MarketplaceAuth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).RefreshToken(ctx, req.(*RefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketplaceAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authproto.MarketplaceAuth",
	HandlerType: (*MarketplaceAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MarketplaceAuth_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _MarketplaceAuth_Register_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _MarketplaceAuth_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_4de06fe703aa931b) }

var fileDescriptor_auth_4de06fe703aa931b = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcf, 0x4f, 0xf2, 0x40,
	0x10, 0xfd, 0x0a, 0x14, 0xda, 0xf9, 0xbe, 0x7c, 0xe8, 0x4a, 0xb4, 0x29, 0x17, 0xec, 0xc5, 0xc6,
	0x03, 0x07, 0xf5, 0xea, 0xc1, 0x83, 0x07, 0x13, 0x7f, 0x24, 0x1b, 0xef, 0xa4, 0xc2, 0x40, 0x1b,
	0x4a, 0x77, 0xdd, 0xdd, 0xc6, 0xf8, 0x77, 0xf9, 0x97, 0xf8, 0x1f, 0x99, 0xd9, 0x52, 0xa0, 0x11,
	0x6e, 0x3b, 0x6f, 0xde, 0xbe, 0xf7, 0x66, 0x06, 0x20, 0x29, 0x4d, 0x3a, 0x96, 0x4a, 0x18, 0xc1,
	0x7c, 0x7a, 0xdb, 0x67, 0xc4, 0xc1, 0x7b, 0x14, 0x8b, 0xac, 0xe0, 0xf8, 0xce, 0x2e, 0xe1, 0xb8,
	0xd4, 0xa8, 0x8a, 0x64, 0x85, 0x13, 0xa1, 0x26, 0xb8, 0x4a, 0xb2, 0x3c, 0x70, 0x46, 0x4e, 0xec,
	0xf3, 0x7e, 0xdd, 0x78, 0x51, 0xf7, 0x04, 0xb3, 0x10, 0x3c, 0x99, 0x68, 0xfd, 0x21, 0xd4, 0x2c,
	0x68, 0x59, 0xca, 0xa6, 0x8e, 0xce, 0xc1, 0x5f, 0x6b, 0x6a, 0xc9, 0x06, 0xe0, 0x1a, 0xb1, 0xc4,
	0x62, 0x2d, 0x54, 0x15, 0xd1, 0x97, 0x03, 0x7f, 0x39, 0x2e, 0x32, 0x6d, 0x50, 0x91, 0xf5, 0x7f,
	0x68, 0x65, 0x33, 0x4b, 0x69, 0xf3, 0x56, 0x36, 0x63, 0x43, 0xf0, 0xc9, 0x71, 0x42, 0x96, 0xb5,
	0x3e, 0x01, 0xcf, 0xc9, 0x0a, 0x49, 0xb2, 0xca, 0xd6, 0xae, 0x24, 0x6d, 0x41, 0xa8, 0x4c, 0x45,
	0x81, 0x41, 0xa7, 0x42, 0x6d, 0xd1, 0xc8, 0xe9, 0x36, 0x73, 0x32, 0x06, 0x1d, 0xf3, 0x29, 0x31,
	0xe8, 0x8e, 0x9c, 0xd8, 0xe5, 0xf6, 0x4d, 0xc6, 0xf3, 0x32, 0xcf, 0x2b, 0xe3, 0x5e, 0xf5, 0x81,
	0x00, 0x32, 0x8e, 0x62, 0xf8, 0xb7, 0x0d, 0xad, 0x25, 0x0b, 0xa0, 0xa7, 0xcb, 0xe9, 0x14, 0xb5,
	0xb6, 0xd1, 0x3d, 0x5e, 0x97, 0xd1, 0x05, 0xf4, 0x39, 0xce, 0x15, 0xea, 0xf4, 0x95, 0xe6, 0xa5,
	0x11, 0xf7, 0x2f, 0x22, 0x86, 0xa3, 0x26, 0xf1, 0xd0, 0xca, 0xae, 0xbe, 0x1d, 0xe8, 0x3f, 0x25,
	0x6a, 0x89, 0x46, 0xe6, 0xc9, 0x14, 0xef, 0x4a, 0x93, 0xb2, 0x1b, 0x70, 0xed, 0xa6, 0xd9, 0xc9,
	0x78, 0x73, 0xd2, 0x71, 0x7d, 0xcf, 0x70, 0xf0, 0x1b, 0xd4, 0x32, 0xfa, 0xc3, 0x6e, 0xc1, 0xab,
	0xc7, 0x60, 0xa7, 0x3b, 0x9c, 0x9d, 0x83, 0x84, 0x67, 0x7b, 0x71, 0xfb, 0xfd, 0x81, 0xb6, 0xb0,
	0x8d, 0xcc, 0xc2, 0x06, 0xb5, 0x31, 0x74, 0x38, 0x3c, 0xd8, 0x23, 0xa9, 0xb7, 0xae, 0xed, 0x5c,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xe6, 0x63, 0xc7, 0x9d, 0x02, 0x00, 0x00,
}
