// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package authproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransferSaldoReq struct {
	SenderId             int64    `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId           int64    `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	TransferAmount       int64    `protobuf:"varint,3,opt,name=transfer_amount,json=transferAmount,proto3" json:"transfer_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferSaldoReq) Reset()         { *m = TransferSaldoReq{} }
func (m *TransferSaldoReq) String() string { return proto.CompactTextString(m) }
func (*TransferSaldoReq) ProtoMessage()    {}
func (*TransferSaldoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *TransferSaldoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferSaldoReq.Unmarshal(m, b)
}
func (m *TransferSaldoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferSaldoReq.Marshal(b, m, deterministic)
}
func (m *TransferSaldoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferSaldoReq.Merge(m, src)
}
func (m *TransferSaldoReq) XXX_Size() int {
	return xxx_messageInfo_TransferSaldoReq.Size(m)
}
func (m *TransferSaldoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferSaldoReq.DiscardUnknown(m)
}

var xxx_messageInfo_TransferSaldoReq proto.InternalMessageInfo

func (m *TransferSaldoReq) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *TransferSaldoReq) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *TransferSaldoReq) GetTransferAmount() int64 {
	if m != nil {
		return m.TransferAmount
	}
	return 0
}

type TransferSaldoResp struct {
	SenderId             int64    `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId           int64    `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	SenderSaldo          int64    `protobuf:"varint,3,opt,name=sender_saldo,json=senderSaldo,proto3" json:"sender_saldo,omitempty"`
	ReceiverSaldo        int64    `protobuf:"varint,4,opt,name=receiver_saldo,json=receiverSaldo,proto3" json:"receiver_saldo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferSaldoResp) Reset()         { *m = TransferSaldoResp{} }
func (m *TransferSaldoResp) String() string { return proto.CompactTextString(m) }
func (*TransferSaldoResp) ProtoMessage()    {}
func (*TransferSaldoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *TransferSaldoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferSaldoResp.Unmarshal(m, b)
}
func (m *TransferSaldoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferSaldoResp.Marshal(b, m, deterministic)
}
func (m *TransferSaldoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferSaldoResp.Merge(m, src)
}
func (m *TransferSaldoResp) XXX_Size() int {
	return xxx_messageInfo_TransferSaldoResp.Size(m)
}
func (m *TransferSaldoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferSaldoResp.DiscardUnknown(m)
}

var xxx_messageInfo_TransferSaldoResp proto.InternalMessageInfo

func (m *TransferSaldoResp) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *TransferSaldoResp) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *TransferSaldoResp) GetSenderSaldo() int64 {
	if m != nil {
		return m.SenderSaldo
	}
	return 0
}

func (m *TransferSaldoResp) GetReceiverSaldo() int64 {
	if m != nil {
		return m.ReceiverSaldo
	}
	return 0
}

type TopUpReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopUpReq) Reset()         { *m = TopUpReq{} }
func (m *TopUpReq) String() string { return proto.CompactTextString(m) }
func (*TopUpReq) ProtoMessage()    {}
func (*TopUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *TopUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopUpReq.Unmarshal(m, b)
}
func (m *TopUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopUpReq.Marshal(b, m, deterministic)
}
func (m *TopUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopUpReq.Merge(m, src)
}
func (m *TopUpReq) XXX_Size() int {
	return xxx_messageInfo_TopUpReq.Size(m)
}
func (m *TopUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TopUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_TopUpReq proto.InternalMessageInfo

func (m *TopUpReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TopUpReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TopUpResp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Saldo                int64    `protobuf:"varint,2,opt,name=saldo,proto3" json:"saldo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopUpResp) Reset()         { *m = TopUpResp{} }
func (m *TopUpResp) String() string { return proto.CompactTextString(m) }
func (*TopUpResp) ProtoMessage()    {}
func (*TopUpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *TopUpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopUpResp.Unmarshal(m, b)
}
func (m *TopUpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopUpResp.Marshal(b, m, deterministic)
}
func (m *TopUpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopUpResp.Merge(m, src)
}
func (m *TopUpResp) XXX_Size() int {
	return xxx_messageInfo_TopUpResp.Size(m)
}
func (m *TopUpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TopUpResp.DiscardUnknown(m)
}

var xxx_messageInfo_TopUpResp proto.InternalMessageInfo

func (m *TopUpResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TopUpResp) GetSaldo() int64 {
	if m != nil {
		return m.Saldo
	}
	return 0
}

type LoginReq struct {
	UsernameOrEmail      string   `protobuf:"bytes,1,opt,name=username_or_email,json=usernameOrEmail,proto3" json:"username_or_email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsernameOrEmail() string {
	if m != nil {
		return m.UsernameOrEmail
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	FullName             string   `protobuf:"bytes,6,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,7,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Province             string   `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	AddressDetail        string   `protobuf:"bytes,10,opt,name=address_detail,json=addressDetail,proto3" json:"address_detail,omitempty"`
	ZipCode              int32    `protobuf:"varint,11,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Description          string   `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RegisterReq) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *RegisterReq) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *RegisterReq) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *RegisterReq) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *RegisterReq) GetAddressDetail() string {
	if m != nil {
		return m.AddressDetail
	}
	return ""
}

func (m *RegisterReq) GetZipCode() int32 {
	if m != nil {
		return m.ZipCode
	}
	return 0
}

func (m *RegisterReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RefreshTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenReq) Reset()         { *m = RefreshTokenReq{} }
func (m *RefreshTokenReq) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenReq) ProtoMessage()    {}
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *RefreshTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenReq.Unmarshal(m, b)
}
func (m *RefreshTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenReq.Marshal(b, m, deterministic)
}
func (m *RefreshTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenReq.Merge(m, src)
}
func (m *RefreshTokenReq) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenReq.Size(m)
}
func (m *RefreshTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenReq proto.InternalMessageInfo

func (m *RefreshTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshTokenResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenResp) Reset()         { *m = RefreshTokenResp{} }
func (m *RefreshTokenResp) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResp) ProtoMessage()    {}
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *RefreshTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResp.Unmarshal(m, b)
}
func (m *RefreshTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResp.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResp.Merge(m, src)
}
func (m *RefreshTokenResp) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResp.Size(m)
}
func (m *RefreshTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResp proto.InternalMessageInfo

func (m *RefreshTokenResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUserReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ProvinceReq struct {
	Province             string   `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvinceReq) Reset()         { *m = ProvinceReq{} }
func (m *ProvinceReq) String() string { return proto.CompactTextString(m) }
func (*ProvinceReq) ProtoMessage()    {}
func (*ProvinceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *ProvinceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvinceReq.Unmarshal(m, b)
}
func (m *ProvinceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvinceReq.Marshal(b, m, deterministic)
}
func (m *ProvinceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvinceReq.Merge(m, src)
}
func (m *ProvinceReq) XXX_Size() int {
	return xxx_messageInfo_ProvinceReq.Size(m)
}
func (m *ProvinceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvinceReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProvinceReq proto.InternalMessageInfo

func (m *ProvinceReq) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

type UserArrayResp struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserArrayResp) Reset()         { *m = UserArrayResp{} }
func (m *UserArrayResp) String() string { return proto.CompactTextString(m) }
func (*UserArrayResp) ProtoMessage()    {}
func (*UserArrayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *UserArrayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserArrayResp.Unmarshal(m, b)
}
func (m *UserArrayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserArrayResp.Marshal(b, m, deterministic)
}
func (m *UserArrayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserArrayResp.Merge(m, src)
}
func (m *UserArrayResp) XXX_Size() int {
	return xxx_messageInfo_UserArrayResp.Size(m)
}
func (m *UserArrayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserArrayResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserArrayResp proto.InternalMessageInfo

func (m *UserArrayResp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*TransferSaldoReq)(nil), "authproto.TransferSaldoReq")
	proto.RegisterType((*TransferSaldoResp)(nil), "authproto.TransferSaldoResp")
	proto.RegisterType((*TopUpReq)(nil), "authproto.TopUpReq")
	proto.RegisterType((*TopUpResp)(nil), "authproto.TopUpResp")
	proto.RegisterType((*LoginReq)(nil), "authproto.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "authproto.LoginResp")
	proto.RegisterType((*RegisterReq)(nil), "authproto.RegisterReq")
	proto.RegisterType((*RefreshTokenReq)(nil), "authproto.RefreshTokenReq")
	proto.RegisterType((*RefreshTokenResp)(nil), "authproto.RefreshTokenResp")
	proto.RegisterType((*GetUserReq)(nil), "authproto.GetUserReq")
	proto.RegisterType((*ProvinceReq)(nil), "authproto.ProvinceReq")
	proto.RegisterType((*UserArrayResp)(nil), "authproto.UserArrayResp")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 721 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xcd, 0x3b, 0xf6, 0x75, 0xd3, 0xb4, 0x43, 0x29, 0xc6, 0x45, 0x22, 0xb5, 0x54, 0x35, 0xb0,
	0xa8, 0x50, 0x0b, 0x2c, 0xca, 0xaa, 0x3c, 0x54, 0x45, 0x2a, 0x14, 0xb9, 0xcd, 0xda, 0x32, 0x99,
	0x69, 0x63, 0x35, 0xf1, 0x0c, 0x33, 0x93, 0xa2, 0xf4, 0x57, 0xf8, 0x12, 0xfe, 0x83, 0x0f, 0x42,
	0xf3, 0x70, 0x6a, 0x87, 0x66, 0x81, 0xd8, 0xcd, 0x3d, 0xf7, 0x71, 0x8e, 0xcf, 0x1d, 0x8d, 0x01,
	0x92, 0x99, 0x1c, 0x1f, 0x30, 0x4e, 0x25, 0x45, 0xae, 0x3a, 0xeb, 0x63, 0x00, 0x33, 0x41, 0xb8,
	0x81, 0xc3, 0x39, 0x6c, 0x5c, 0xf2, 0x24, 0x13, 0x57, 0x84, 0x5f, 0x24, 0x13, 0x4c, 0x23, 0xf2,
	0x1d, 0xed, 0x80, 0x2b, 0x48, 0x86, 0x09, 0x8f, 0x53, 0xec, 0x57, 0x7b, 0xd5, 0x7e, 0x3d, 0x72,
	0x0c, 0x30, 0xc0, 0xe8, 0x39, 0x78, 0x9c, 0x8c, 0x48, 0x7a, 0x6b, 0xd2, 0x35, 0x9d, 0x86, 0x1c,
	0x1a, 0x60, 0xb4, 0x0f, 0x5d, 0x69, 0x27, 0xc6, 0xc9, 0x94, 0xce, 0x32, 0xe9, 0xd7, 0x75, 0xd1,
	0x7a, 0x0e, 0x9f, 0x68, 0x34, 0xfc, 0x59, 0x85, 0xcd, 0x25, 0x6e, 0xc1, 0xfe, 0x93, 0x7c, 0x17,
	0xd6, 0x6c, 0xb7, 0x50, 0x13, 0x2d, 0xb3, 0x67, 0x30, 0x4d, 0x82, 0xf6, 0x60, 0x7d, 0x31, 0xc3,
	0x14, 0x35, 0x74, 0x51, 0x27, 0x47, 0x75, 0x59, 0xf8, 0x0e, 0x9c, 0x4b, 0xca, 0x86, 0x4c, 0x19,
	0xf2, 0x04, 0xda, 0xca, 0xb2, 0x7b, 0x45, 0x2d, 0x15, 0x0e, 0x30, 0xda, 0x86, 0x96, 0xfd, 0x44,
	0x23, 0xc5, 0x46, 0xe1, 0x31, 0xb8, 0xb6, 0x59, 0xb0, 0xd5, 0xdd, 0x5b, 0xd0, 0x34, 0x02, 0x4c,
	0xb3, 0x09, 0xc2, 0x08, 0x9c, 0x33, 0x7a, 0x9d, 0x66, 0x8a, 0xf8, 0x25, 0x6c, 0xaa, 0xda, 0x2c,
	0x99, 0x92, 0x98, 0xf2, 0x98, 0x4c, 0x93, 0x74, 0xa2, 0x87, 0xb8, 0x51, 0x37, 0x4f, 0x9c, 0xf3,
	0x4f, 0x0a, 0x46, 0x01, 0x38, 0x2c, 0x11, 0xe2, 0x07, 0xe5, 0xc6, 0x18, 0x37, 0x5a, 0xc4, 0xe1,
	0x2e, 0xb8, 0x76, 0xa6, 0x60, 0x8a, 0x56, 0xd2, 0x1b, 0x92, 0xd9, 0x41, 0x26, 0x08, 0x7f, 0xd7,
	0xc0, 0x8b, 0xc8, 0x75, 0x2a, 0x24, 0xe1, 0xf6, 0x12, 0x68, 0xd5, 0x8a, 0xc2, 0x56, 0x3a, 0x0a,
	0xf8, 0x92, 0x4c, 0x89, 0x1a, 0x61, 0xb4, 0x18, 0x22, 0x13, 0x28, 0x94, 0x8d, 0x69, 0x46, 0xb4,
	0xeb, 0x6e, 0x64, 0x82, 0x92, 0xae, 0x46, 0x59, 0x17, 0x42, 0xd0, 0x90, 0x73, 0x46, 0xfc, 0x66,
	0xaf, 0xda, 0x6f, 0x46, 0xfa, 0xac, 0x88, 0xaf, 0x66, 0x93, 0x89, 0x21, 0x6e, 0x99, 0x06, 0x05,
	0x68, 0xe2, 0x1d, 0x70, 0xd9, 0x98, 0x4a, 0x1a, 0xcf, 0xf8, 0xc4, 0x6f, 0xdb, 0x69, 0x0a, 0x18,
	0x72, 0xe3, 0x00, 0xa7, 0xb7, 0x69, 0x36, 0x22, 0xbe, 0x63, 0x73, 0x36, 0x56, 0x4c, 0xa3, 0x54,
	0xce, 0x7d, 0x57, 0xe3, 0xfa, 0xac, 0x6e, 0x42, 0x82, 0x31, 0x27, 0x42, 0xc4, 0x98, 0x48, 0xf5,
	0x39, 0xa0, 0xb3, 0x1d, 0x8b, 0x7e, 0xd4, 0x20, 0x7a, 0x0a, 0xce, 0x5d, 0xca, 0xe2, 0x11, 0xc5,
	0xc4, 0xf7, 0xb4, 0xd0, 0xf6, 0x5d, 0xca, 0x3e, 0x50, 0x4c, 0x50, 0x0f, 0x3c, 0x4c, 0xc4, 0x88,
	0xa7, 0x4c, 0xa6, 0x34, 0xf3, 0xd7, 0x74, 0x7b, 0x11, 0x0a, 0xf7, 0xa1, 0x1b, 0x91, 0x2b, 0x4e,
	0xc4, 0xf8, 0x52, 0xd9, 0xac, 0x9c, 0x7d, 0xd8, 0xff, 0x3e, 0x6c, 0x94, 0x0b, 0x57, 0x6e, 0xea,
	0x1c, 0xe0, 0x94, 0xc8, 0xa1, 0x30, 0x7b, 0x5a, 0x87, 0xda, 0xe2, 0x62, 0xd5, 0x52, 0x5c, 0xde,
	0x5b, 0x6d, 0xd5, 0xde, 0xea, 0x85, 0xbd, 0x85, 0x2f, 0xc0, 0xfb, 0x6a, 0x7d, 0x52, 0x13, 0x8b,
	0x36, 0x56, 0xcb, 0x36, 0x86, 0x6f, 0xa1, 0xa3, 0x88, 0x4f, 0x38, 0x4f, 0xe6, 0x5a, 0xe2, 0x1e,
	0x34, 0xd5, 0x74, 0xe1, 0x57, 0x7b, 0xf5, 0xbe, 0x77, 0xd8, 0x3d, 0x58, 0x3c, 0x33, 0x07, 0x5a,
	0xa1, 0xc9, 0x1e, 0xfe, 0x6a, 0x40, 0xf7, 0x73, 0xc2, 0x6f, 0x88, 0x64, 0x93, 0x64, 0x44, 0x4e,
	0x66, 0x72, 0x8c, 0x5e, 0x43, 0x53, 0x5f, 0x4a, 0xf4, 0xa8, 0xd0, 0x94, 0x5f, 0xfd, 0x60, 0xeb,
	0x6f, 0x50, 0xb0, 0xb0, 0x82, 0xde, 0x80, 0x93, 0x5f, 0x53, 0xb4, 0x5d, 0xa8, 0x29, 0xdc, 0xdd,
	0x60, 0x59, 0x45, 0x58, 0x41, 0x03, 0x58, 0x2b, 0xda, 0x8b, 0x82, 0x52, 0x6b, 0x69, 0x41, 0xc1,
	0xce, 0xca, 0x9c, 0x56, 0x70, 0x04, 0x6d, 0xeb, 0x3f, 0x7a, 0x5c, 0xa8, 0xbc, 0xdf, 0xc9, 0x43,
	0xfc, 0xaf, 0x00, 0x86, 0x0c, 0x27, 0x92, 0xe8, 0xbe, 0xe5, 0x82, 0x87, 0x3a, 0x4e, 0x61, 0xf3,
	0x94, 0xc8, 0x8b, 0x31, 0x65, 0xef, 0xe7, 0xf9, 0x7a, 0x4a, 0x5f, 0x5c, 0xd8, 0x59, 0xe0, 0x2f,
	0xf5, 0x2f, 0x16, 0x14, 0x56, 0x94, 0xcf, 0xfa, 0x31, 0x2a, 0xf9, 0x9c, 0xbf, 0x6d, 0x25, 0x9f,
	0x17, 0x6f, 0x56, 0x58, 0x41, 0xc7, 0xe0, 0x19, 0xc1, 0xe6, 0xd5, 0xfc, 0xa7, 0xde, 0x33, 0xe8,
	0x94, 0x1e, 0x76, 0x54, 0x74, 0x74, 0xf9, 0x77, 0x13, 0x3c, 0x5b, 0x9d, 0x54, 0xd3, 0xbe, 0xb5,
	0x74, 0xea, 0xe8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0x95, 0xad, 0xa2, 0xce, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MarketplaceAuthClient is the client API for MarketplaceAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketplaceAuthClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*User, error)
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	GetShopByProvince(ctx context.Context, in *ProvinceReq, opts ...grpc.CallOption) (*UserArrayResp, error)
	// Payment
	TopUp(ctx context.Context, in *TopUpReq, opts ...grpc.CallOption) (*TopUpResp, error)
	UpdateSaldo(ctx context.Context, in *TopUpReq, opts ...grpc.CallOption) (*TopUpResp, error)
	TransferSaldo(ctx context.Context, in *TransferSaldoReq, opts ...grpc.CallOption) (*TransferSaldoResp, error)
}

type marketplaceAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketplaceAuthClient(cc grpc.ClientConnInterface) MarketplaceAuthClient {
	return &marketplaceAuthClient{cc}
}

func (c *marketplaceAuthClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	out := new(RefreshTokenResp)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) GetShopByProvince(ctx context.Context, in *ProvinceReq, opts ...grpc.CallOption) (*UserArrayResp, error) {
	out := new(UserArrayResp)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/GetShopByProvince", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) TopUp(ctx context.Context, in *TopUpReq, opts ...grpc.CallOption) (*TopUpResp, error) {
	out := new(TopUpResp)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/TopUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) UpdateSaldo(ctx context.Context, in *TopUpReq, opts ...grpc.CallOption) (*TopUpResp, error) {
	out := new(TopUpResp)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/UpdateSaldo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceAuthClient) TransferSaldo(ctx context.Context, in *TransferSaldoReq, opts ...grpc.CallOption) (*TransferSaldoResp, error) {
	out := new(TransferSaldoResp)
	err := c.cc.Invoke(ctx, "/authproto.MarketplaceAuth/TransferSaldo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketplaceAuthServer is the server API for MarketplaceAuth service.
type MarketplaceAuthServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	Register(context.Context, *RegisterReq) (*User, error)
	RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenResp, error)
	GetUser(context.Context, *GetUserReq) (*User, error)
	UpdateUser(context.Context, *User) (*User, error)
	GetShopByProvince(context.Context, *ProvinceReq) (*UserArrayResp, error)
	// Payment
	TopUp(context.Context, *TopUpReq) (*TopUpResp, error)
	UpdateSaldo(context.Context, *TopUpReq) (*TopUpResp, error)
	TransferSaldo(context.Context, *TransferSaldoReq) (*TransferSaldoResp, error)
}

// UnimplementedMarketplaceAuthServer can be embedded to have forward compatible implementations.
type UnimplementedMarketplaceAuthServer struct {
}

func (*UnimplementedMarketplaceAuthServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedMarketplaceAuthServer) Register(ctx context.Context, req *RegisterReq) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedMarketplaceAuthServer) RefreshToken(ctx context.Context, req *RefreshTokenReq) (*RefreshTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (*UnimplementedMarketplaceAuthServer) GetUser(ctx context.Context, req *GetUserReq) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedMarketplaceAuthServer) UpdateUser(ctx context.Context, req *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedMarketplaceAuthServer) GetShopByProvince(ctx context.Context, req *ProvinceReq) (*UserArrayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopByProvince not implemented")
}
func (*UnimplementedMarketplaceAuthServer) TopUp(ctx context.Context, req *TopUpReq) (*TopUpResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopUp not implemented")
}
func (*UnimplementedMarketplaceAuthServer) UpdateSaldo(ctx context.Context, req *TopUpReq) (*TopUpResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSaldo not implemented")
}
func (*UnimplementedMarketplaceAuthServer) TransferSaldo(ctx context.Context, req *TransferSaldoReq) (*TransferSaldoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferSaldo not implemented")
}

func RegisterMarketplaceAuthServer(s *grpc.Server, srv MarketplaceAuthServer) {
	s.RegisterService(&_MarketplaceAuth_serviceDesc, srv)
}

func _MarketplaceAuth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).RefreshToken(ctx, req.(*RefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_GetShopByProvince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvinceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).GetShopByProvince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/GetShopByProvince",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).GetShopByProvince(ctx, req.(*ProvinceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_TopUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).TopUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/TopUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).TopUp(ctx, req.(*TopUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_UpdateSaldo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).UpdateSaldo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/UpdateSaldo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).UpdateSaldo(ctx, req.(*TopUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceAuth_TransferSaldo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferSaldoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceAuthServer).TransferSaldo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authproto.MarketplaceAuth/TransferSaldo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceAuthServer).TransferSaldo(ctx, req.(*TransferSaldoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketplaceAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authproto.MarketplaceAuth",
	HandlerType: (*MarketplaceAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MarketplaceAuth_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _MarketplaceAuth_Register_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _MarketplaceAuth_RefreshToken_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _MarketplaceAuth_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _MarketplaceAuth_UpdateUser_Handler,
		},
		{
			MethodName: "GetShopByProvince",
			Handler:    _MarketplaceAuth_GetShopByProvince_Handler,
		},
		{
			MethodName: "TopUp",
			Handler:    _MarketplaceAuth_TopUp_Handler,
		},
		{
			MethodName: "UpdateSaldo",
			Handler:    _MarketplaceAuth_UpdateSaldo_Handler,
		},
		{
			MethodName: "TransferSaldo",
			Handler:    _MarketplaceAuth_TransferSaldo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
