// Code generated by protoc-gen-go. DO NOT EDIT.
// source: saldohistory.proto

package authproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaldoHistory struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SourceId             int64    `protobuf:"varint,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ChangeAmount         int64    `protobuf:"varint,5,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaldoHistory) Reset()         { *m = SaldoHistory{} }
func (m *SaldoHistory) String() string { return proto.CompactTextString(m) }
func (*SaldoHistory) ProtoMessage()    {}
func (*SaldoHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6bab2d58559741d, []int{0}
}

func (m *SaldoHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaldoHistory.Unmarshal(m, b)
}
func (m *SaldoHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaldoHistory.Marshal(b, m, deterministic)
}
func (m *SaldoHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaldoHistory.Merge(m, src)
}
func (m *SaldoHistory) XXX_Size() int {
	return xxx_messageInfo_SaldoHistory.Size(m)
}
func (m *SaldoHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_SaldoHistory.DiscardUnknown(m)
}

var xxx_messageInfo_SaldoHistory proto.InternalMessageInfo

func (m *SaldoHistory) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaldoHistory) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SaldoHistory) GetSourceId() int64 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *SaldoHistory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SaldoHistory) GetChangeAmount() int64 {
	if m != nil {
		return m.ChangeAmount
	}
	return 0
}

func (m *SaldoHistory) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *SaldoHistory) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*SaldoHistory)(nil), "authproto.SaldoHistory")
}

func init() {
	proto.RegisterFile("saldohistory.proto", fileDescriptor_f6bab2d58559741d)
}

var fileDescriptor_f6bab2d58559741d = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xb1, 0x4a, 0xc5, 0x30,
	0x14, 0xc6, 0x71, 0xd2, 0xab, 0xbd, 0xe6, 0x78, 0x75, 0x38, 0x8b, 0x01, 0x11, 0x8a, 0x2e, 0x77,
	0x72, 0xf1, 0x09, 0xba, 0xd9, 0xb5, 0x3e, 0x40, 0x89, 0x39, 0xc1, 0x06, 0xb4, 0x29, 0xc9, 0xc9,
	0xe0, 0xa3, 0xfa, 0x36, 0xd2, 0x93, 0x0a, 0x6e, 0xc9, 0xef, 0xff, 0x11, 0x08, 0x60, 0xb6, 0x9f,
	0x14, 0xe7, 0x90, 0x39, 0xa6, 0xef, 0xe7, 0x35, 0x45, 0x8e, 0xa8, 0x6d, 0xe1, 0x59, 0x8e, 0x8f,
	0x3f, 0x0a, 0x4e, 0x6f, 0xdb, 0xe2, 0xb5, 0x2e, 0xf0, 0x16, 0x9a, 0x40, 0x46, 0x75, 0xea, 0x7c,
	0x18, 0x9b, 0x40, 0x78, 0x07, 0xc7, 0x92, 0x7d, 0x9a, 0x02, 0x99, 0x46, 0xb0, 0xdd, 0xae, 0x03,
	0xe1, 0x3d, 0xe8, 0x1c, 0x4b, 0x72, 0x7e, 0x4b, 0x07, 0x49, 0x57, 0x15, 0x06, 0xc2, 0x0e, 0xae,
	0xc9, 0x67, 0x97, 0xc2, 0xca, 0x21, 0x2e, 0xe6, 0xa2, 0x53, 0x67, 0x3d, 0xfe, 0x27, 0x7c, 0x82,
	0x1b, 0x37, 0xdb, 0xe5, 0xc3, 0x4f, 0xf6, 0x2b, 0x96, 0x85, 0xcd, 0xa5, 0x3c, 0x71, 0xaa, 0xd8,
	0x8b, 0xe1, 0x03, 0x80, 0x4b, 0xde, 0xb2, 0xa7, 0xc9, 0xb2, 0x69, 0x65, 0xa1, 0x77, 0xe9, 0x25,
	0x97, 0x95, 0xfe, 0xf2, 0xb1, 0xe6, 0x5d, 0x7a, 0x7e, 0x6f, 0xe5, 0x8b, 0x2f, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xd3, 0x24, 0x23, 0xa4, 0x03, 0x01, 0x00, 0x00,
}
