// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package authproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,6,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Type                 int32    `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            int64    `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Province             string   `protobuf:"bytes,11,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	AddressDetail        string   `protobuf:"bytes,13,opt,name=address_detail,json=addressDetail,proto3" json:"address_detail,omitempty"`
	ZipCode              int32    `protobuf:"varint,14,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Description          string   `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	NewPassword          string   `protobuf:"bytes,16,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Saldo                int64    `protobuf:"varint,17,opt,name=saldo,proto3" json:"saldo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *User) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *User) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *User) GetAddressDetail() string {
	if m != nil {
		return m.AddressDetail
	}
	return ""
}

func (m *User) GetZipCode() int32 {
	if m != nil {
		return m.ZipCode
	}
	return 0
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *User) GetSaldo() int64 {
	if m != nil {
		return m.Saldo
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "authproto.User")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x18, 0xc5, 0xe9, 0xb6, 0x6e, 0xed, 0xb7, 0x3f, 0x6a, 0xd8, 0x45, 0x54, 0x84, 0x2a, 0x08, 0xbb,
	0xf2, 0xc6, 0x27, 0x18, 0x7a, 0x2d, 0x32, 0xd8, 0x75, 0x89, 0xcd, 0x07, 0x0b, 0x74, 0x4d, 0x48,
	0x52, 0xcb, 0xf6, 0x8a, 0xbe, 0x94, 0xe4, 0x4b, 0x26, 0xde, 0x9d, 0xf3, 0x3b, 0xe9, 0x69, 0x4f,
	0x03, 0xd0, 0x3b, 0xb4, 0x2f, 0xc6, 0x6a, 0xaf, 0x59, 0x29, 0x7a, 0x7f, 0x20, 0xf9, 0xf4, 0x33,
	0x86, 0xc9, 0xde, 0xa1, 0x65, 0x2b, 0x18, 0x29, 0xc9, 0xb3, 0x2a, 0xdb, 0x8c, 0x77, 0x23, 0x25,
	0x19, 0x83, 0x49, 0x27, 0x8e, 0xc8, 0x47, 0x55, 0xb6, 0x29, 0x77, 0xa4, 0xd9, 0x3d, 0x94, 0xa1,
	0xa5, 0xa6, 0x60, 0x4c, 0x41, 0x11, 0xc0, 0x47, 0x08, 0xd7, 0x90, 0xe3, 0x51, 0xa8, 0x96, 0x4f,
	0x28, 0x88, 0x26, 0x50, 0x73, 0xd0, 0x1d, 0xf2, 0x3c, 0x52, 0x32, 0xa1, 0xc8, 0x1c, 0xb4, 0xd7,
	0x75, 0x6f, 0x5b, 0x3e, 0x8d, 0x45, 0x04, 0xf6, 0xb6, 0x0d, 0x6f, 0xf6, 0x27, 0x83, 0x7c, 0x56,
	0x65, 0x9b, 0x7c, 0x47, 0x9a, 0xdd, 0x41, 0x61, 0x84, 0x73, 0x83, 0xb6, 0x92, 0x17, 0xe9, 0x7c,
	0xf2, 0xec, 0x01, 0xa0, 0xb1, 0x28, 0x3c, 0xca, 0x5a, 0x78, 0x5e, 0xd2, 0x82, 0x32, 0x91, 0xad,
	0x0f, 0x71, 0x6f, 0xe4, 0x25, 0x86, 0x18, 0x27, 0xb2, 0xf5, 0xd4, 0x6c, 0xf5, 0xb7, 0xea, 0x1a,
	0xe4, 0xf3, 0xd4, 0x9c, 0x7c, 0xf8, 0x92, 0x46, 0xf9, 0x13, 0x5f, 0xc4, 0x7f, 0x10, 0x34, 0x7b,
	0x86, 0x95, 0x90, 0xd2, 0xa2, 0x73, 0xb5, 0x44, 0x1f, 0xf6, 0x2e, 0x29, 0x5d, 0x26, 0xfa, 0x4e,
	0x90, 0xdd, 0x42, 0x71, 0x56, 0xa6, 0x6e, 0xb4, 0x44, 0xbe, 0xa2, 0x21, 0xb3, 0xb3, 0x32, 0x6f,
	0x5a, 0x22, 0xab, 0x60, 0x2e, 0xd1, 0x35, 0x56, 0x19, 0xaf, 0x74, 0xc7, 0xaf, 0xe8, 0xf1, 0xff,
	0x88, 0x3d, 0xc2, 0xa2, 0xc3, 0xa1, 0xfe, 0x5b, 0x7c, 0x1d, 0x8f, 0x74, 0x38, 0x7c, 0x5e, 0x46,
	0xaf, 0x21, 0x77, 0xa2, 0x95, 0x9a, 0xdf, 0xd0, 0xa0, 0x68, 0xbe, 0xa6, 0x74, 0xa9, 0xaf, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x87, 0x2e, 0x25, 0xed, 0x01, 0x00, 0x00,
}
