// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/idzharbae/marketplace-backend/svc/auth/internal (interfaces: SaldoHistoryWriter)

// Package repomock is a generated GoMock package.
package repomock

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/idzharbae/marketplace-backend/svc/auth/internal/entity"
	reflect "reflect"
)

// MockSaldoHistoryWriter is a mock of SaldoHistoryWriter interface.
type MockSaldoHistoryWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSaldoHistoryWriterMockRecorder
}

// MockSaldoHistoryWriterMockRecorder is the mock recorder for MockSaldoHistoryWriter.
type MockSaldoHistoryWriterMockRecorder struct {
	mock *MockSaldoHistoryWriter
}

// NewMockSaldoHistoryWriter creates a new mock instance.
func NewMockSaldoHistoryWriter(ctrl *gomock.Controller) *MockSaldoHistoryWriter {
	mock := &MockSaldoHistoryWriter{ctrl: ctrl}
	mock.recorder = &MockSaldoHistoryWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaldoHistoryWriter) EXPECT() *MockSaldoHistoryWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSaldoHistoryWriter) Create(arg0 entity.SaldoHistory) (entity.SaldoHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(entity.SaldoHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSaldoHistoryWriterMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSaldoHistoryWriter)(nil).Create), arg0)
}
