// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package catalogproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListProductsReq struct {
	ShopID               int32       `protobuf:"varint,1,opt,name=shopID,proto3" json:"shopID,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListProductsReq) Reset()         { *m = ListProductsReq{} }
func (m *ListProductsReq) String() string { return proto.CompactTextString(m) }
func (*ListProductsReq) ProtoMessage()    {}
func (*ListProductsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{0}
}

func (m *ListProductsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsReq.Unmarshal(m, b)
}
func (m *ListProductsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsReq.Marshal(b, m, deterministic)
}
func (m *ListProductsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsReq.Merge(m, src)
}
func (m *ListProductsReq) XXX_Size() int {
	return xxx_messageInfo_ListProductsReq.Size(m)
}
func (m *ListProductsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsReq proto.InternalMessageInfo

func (m *ListProductsReq) GetShopID() int32 {
	if m != nil {
		return m.ShopID
	}
	return 0
}

func (m *ListProductsReq) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ListProductsResp struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProductsResp) Reset()         { *m = ListProductsResp{} }
func (m *ListProductsResp) String() string { return proto.CompactTextString(m) }
func (*ListProductsResp) ProtoMessage()    {}
func (*ListProductsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{1}
}

func (m *ListProductsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsResp.Unmarshal(m, b)
}
func (m *ListProductsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsResp.Marshal(b, m, deterministic)
}
func (m *ListProductsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsResp.Merge(m, src)
}
func (m *ListProductsResp) XXX_Size() int {
	return xxx_messageInfo_ListProductsResp.Size(m)
}
func (m *ListProductsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsResp proto.InternalMessageInfo

func (m *ListProductsResp) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type GetProductReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductReq) Reset()         { *m = GetProductReq{} }
func (m *GetProductReq) String() string { return proto.CompactTextString(m) }
func (*GetProductReq) ProtoMessage()    {}
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2}
}

func (m *GetProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductReq.Unmarshal(m, b)
}
func (m *GetProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductReq.Marshal(b, m, deterministic)
}
func (m *GetProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductReq.Merge(m, src)
}
func (m *GetProductReq) XXX_Size() int {
	return xxx_messageInfo_GetProductReq.Size(m)
}
func (m *GetProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductReq proto.InternalMessageInfo

func (m *GetProductReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetProductReq) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type PKReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PKReq) Reset()         { *m = PKReq{} }
func (m *PKReq) String() string { return proto.CompactTextString(m) }
func (*PKReq) ProtoMessage()    {}
func (*PKReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{3}
}

func (m *PKReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PKReq.Unmarshal(m, b)
}
func (m *PKReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PKReq.Marshal(b, m, deterministic)
}
func (m *PKReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PKReq.Merge(m, src)
}
func (m *PKReq) XXX_Size() int {
	return xxx_messageInfo_PKReq.Size(m)
}
func (m *PKReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PKReq.DiscardUnknown(m)
}

var xxx_messageInfo_PKReq proto.InternalMessageInfo

func (m *PKReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListShopsReq struct {
	Pagination           *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListShopsReq) Reset()         { *m = ListShopsReq{} }
func (m *ListShopsReq) String() string { return proto.CompactTextString(m) }
func (*ListShopsReq) ProtoMessage()    {}
func (*ListShopsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{4}
}

func (m *ListShopsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShopsReq.Unmarshal(m, b)
}
func (m *ListShopsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShopsReq.Marshal(b, m, deterministic)
}
func (m *ListShopsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShopsReq.Merge(m, src)
}
func (m *ListShopsReq) XXX_Size() int {
	return xxx_messageInfo_ListShopsReq.Size(m)
}
func (m *ListShopsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShopsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListShopsReq proto.InternalMessageInfo

func (m *ListShopsReq) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ListShopsResp struct {
	Shops                []*Shop  `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListShopsResp) Reset()         { *m = ListShopsResp{} }
func (m *ListShopsResp) String() string { return proto.CompactTextString(m) }
func (*ListShopsResp) ProtoMessage()    {}
func (*ListShopsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{5}
}

func (m *ListShopsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShopsResp.Unmarshal(m, b)
}
func (m *ListShopsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShopsResp.Marshal(b, m, deterministic)
}
func (m *ListShopsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShopsResp.Merge(m, src)
}
func (m *ListShopsResp) XXX_Size() int {
	return xxx_messageInfo_ListShopsResp.Size(m)
}
func (m *ListShopsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShopsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListShopsResp proto.InternalMessageInfo

func (m *ListShopsResp) GetShops() []*Shop {
	if m != nil {
		return m.Shops
	}
	return nil
}

type GetShopReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopReq) Reset()         { *m = GetShopReq{} }
func (m *GetShopReq) String() string { return proto.CompactTextString(m) }
func (*GetShopReq) ProtoMessage()    {}
func (*GetShopReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{6}
}

func (m *GetShopReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopReq.Unmarshal(m, b)
}
func (m *GetShopReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopReq.Marshal(b, m, deterministic)
}
func (m *GetShopReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopReq.Merge(m, src)
}
func (m *GetShopReq) XXX_Size() int {
	return xxx_messageInfo_GetShopReq.Size(m)
}
func (m *GetShopReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopReq proto.InternalMessageInfo

func (m *GetShopReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetShopReq) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func init() {
	proto.RegisterType((*ListProductsReq)(nil), "catalogproto.ListProductsReq")
	proto.RegisterType((*ListProductsResp)(nil), "catalogproto.ListProductsResp")
	proto.RegisterType((*GetProductReq)(nil), "catalogproto.GetProductReq")
	proto.RegisterType((*PKReq)(nil), "catalogproto.PKReq")
	proto.RegisterType((*ListShopsReq)(nil), "catalogproto.ListShopsReq")
	proto.RegisterType((*ListShopsResp)(nil), "catalogproto.ListShopsResp")
	proto.RegisterType((*GetShopReq)(nil), "catalogproto.GetShopReq")
}

func init() {
	proto.RegisterFile("catalog.proto", fileDescriptor_0abbfcf058acdf89)
}

var fileDescriptor_0abbfcf058acdf89 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x4d, 0xd8, 0xc2, 0xc6, 0x85, 0x6c, 0xd3, 0x9d, 0xb6, 0x45, 0x41, 0x9b, 0x90, 0x9f, 0xf2,
	0x84, 0x36, 0x90, 0xa6, 0xf1, 0x30, 0x4d, 0x1a, 0x30, 0x56, 0xb5, 0x55, 0x51, 0xaa, 0x7e, 0x80,
	0x49, 0x2c, 0x88, 0x9a, 0x12, 0x37, 0x36, 0x0f, 0xfd, 0x9d, 0x7e, 0x69, 0x15, 0x3b, 0xa1, 0x04,
	0x02, 0x2d, 0xea, 0x9b, 0xaf, 0xef, 0xb9, 0xc7, 0xe7, 0x9c, 0x6b, 0xb0, 0x03, 0x2a, 0x69, 0x9c,
	0xcc, 0xbb, 0x3c, 0x4d, 0x64, 0x82, 0xad, 0xbc, 0x54, 0x95, 0x6b, 0xf3, 0x34, 0x09, 0x57, 0x81,
	0xd4, 0x4d, 0x17, 0xc4, 0x22, 0xe1, 0xc5, 0x79, 0x46, 0x05, 0xd3, 0x67, 0x12, 0xc0, 0xfb, 0xb3,
	0x48, 0xc8, 0xa9, 0x06, 0x0b, 0x9f, 0xdd, 0xe2, 0x67, 0xa8, 0x67, 0xe0, 0x93, 0x91, 0x63, 0x76,
	0x4c, 0xcf, 0xf2, 0xf3, 0x0a, 0x7f, 0x01, 0x70, 0x3a, 0x8f, 0x96, 0x54, 0x46, 0xc9, 0xd2, 0xa9,
	0x75, 0x4c, 0xaf, 0xd9, 0x73, 0xba, 0x9b, 0x8f, 0x76, 0xa7, 0xeb, 0xbe, 0xbf, 0x81, 0x25, 0x63,
	0xf8, 0x50, 0x7e, 0x44, 0x70, 0xfc, 0x01, 0x6f, 0x73, 0x85, 0xc2, 0x31, 0x3b, 0xaf, 0xbc, 0x66,
	0xef, 0xd3, 0x16, 0x97, 0xee, 0xfa, 0x6b, 0x18, 0xe9, 0x83, 0x3d, 0x61, 0x05, 0x4b, 0xa6, 0xf4,
	0x1d, 0xd4, 0xa2, 0x30, 0x57, 0x59, 0x8b, 0x42, 0x44, 0x78, 0x2d, 0xe2, 0xd5, 0x5c, 0x69, 0x6b,
	0xf8, 0xea, 0x4c, 0xbe, 0x80, 0x35, 0x3d, 0xad, 0x00, 0x93, 0xff, 0xd0, 0xca, 0x44, 0x5d, 0x2e,
	0x12, 0xae, 0x6c, 0x97, 0xed, 0x99, 0x47, 0xd8, 0x1b, 0x80, 0xbd, 0xc1, 0x24, 0x38, 0x7a, 0x60,
	0x65, 0x99, 0x15, 0xc6, 0xb0, 0xcc, 0x92, 0xe1, 0x7c, 0x0d, 0x20, 0xdf, 0x01, 0x26, 0x4c, 0x4d,
	0x3e, 0xd3, 0x4f, 0xef, 0xde, 0x02, 0x3c, 0xa7, 0xe9, 0x35, 0x93, 0x3c, 0xa6, 0x01, 0x1b, 0x6a,
	0x66, 0xbc, 0xd0, 0x6e, 0x8a, 0x88, 0xf1, 0x6b, 0xf9, 0xcd, 0xad, 0x1d, 0xbb, 0xdf, 0x0e, 0xb5,
	0x05, 0x27, 0x06, 0xfe, 0x55, 0xca, 0xf2, 0x4b, 0x6c, 0x97, 0xf1, 0xa5, 0x35, 0xb8, 0xd5, 0x8b,
	0x23, 0x06, 0xfe, 0x01, 0x7b, 0x98, 0x32, 0x2a, 0x59, 0x41, 0x53, 0x8d, 0x3c, 0x48, 0x70, 0xc5,
	0xc3, 0x17, 0x10, 0x0c, 0xc1, 0x1e, 0xb1, 0x98, 0x3d, 0x12, 0x1c, 0x34, 0xf2, 0xb1, 0xdc, 0x1c,
	0xdf, 0x70, 0x79, 0x47, 0x0c, 0xfc, 0x07, 0x8d, 0xf5, 0x7e, 0xd1, 0xdd, 0x4d, 0xae, 0xf8, 0x42,
	0x6e, 0x7b, 0x6f, 0x4f, 0x45, 0x3a, 0x80, 0x37, 0xf9, 0xb2, 0xd1, 0xd9, 0x91, 0x91, 0xff, 0x01,
	0xb7, 0xe2, 0xb3, 0x10, 0x03, 0x7f, 0x02, 0xe8, 0x24, 0xd5, 0x74, 0x05, 0x66, 0xff, 0x9c, 0x0e,
	0xf0, 0xc8, 0xb9, 0xdf, 0x00, 0x3a, 0xb7, 0x27, 0xd4, 0x56, 0x27, 0x36, 0xab, 0xab, 0xb2, 0xff,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xe0, 0x6d, 0xca, 0xa2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MarketplaceCatalogClient is the client API for MarketplaceCatalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketplaceCatalogClient interface {
	// Product
	ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error)
	GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*Product, error)
	CreateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error)
	UpdateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error)
	DeleteProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*Empty, error)
	// Shop
	ListShops(ctx context.Context, in *ListShopsReq, opts ...grpc.CallOption) (*ListShopsResp, error)
	GetShop(ctx context.Context, in *GetShopReq, opts ...grpc.CallOption) (*Shop, error)
	CreateShop(ctx context.Context, in *Shop, opts ...grpc.CallOption) (*Shop, error)
	UpdateShop(ctx context.Context, in *Shop, opts ...grpc.CallOption) (*Shop, error)
	DeleteShop(ctx context.Context, in *GetShopReq, opts ...grpc.CallOption) (*Empty, error)
}

type marketplaceCatalogClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketplaceCatalogClient(cc grpc.ClientConnInterface) MarketplaceCatalogClient {
	return &marketplaceCatalogClient{cc}
}

func (c *marketplaceCatalogClient) ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error) {
	out := new(ListProductsResp)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceCatalogClient) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceCatalogClient) CreateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceCatalogClient) UpdateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceCatalogClient) DeleteProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceCatalogClient) ListShops(ctx context.Context, in *ListShopsReq, opts ...grpc.CallOption) (*ListShopsResp, error) {
	out := new(ListShopsResp)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/ListShops", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceCatalogClient) GetShop(ctx context.Context, in *GetShopReq, opts ...grpc.CallOption) (*Shop, error) {
	out := new(Shop)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/GetShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceCatalogClient) CreateShop(ctx context.Context, in *Shop, opts ...grpc.CallOption) (*Shop, error) {
	out := new(Shop)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/CreateShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceCatalogClient) UpdateShop(ctx context.Context, in *Shop, opts ...grpc.CallOption) (*Shop, error) {
	out := new(Shop)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/UpdateShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceCatalogClient) DeleteShop(ctx context.Context, in *GetShopReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/catalogproto.MarketplaceCatalog/DeleteShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketplaceCatalogServer is the server API for MarketplaceCatalog service.
type MarketplaceCatalogServer interface {
	// Product
	ListProducts(context.Context, *ListProductsReq) (*ListProductsResp, error)
	GetProduct(context.Context, *GetProductReq) (*Product, error)
	CreateProduct(context.Context, *Product) (*Product, error)
	UpdateProduct(context.Context, *Product) (*Product, error)
	DeleteProduct(context.Context, *GetProductReq) (*Empty, error)
	// Shop
	ListShops(context.Context, *ListShopsReq) (*ListShopsResp, error)
	GetShop(context.Context, *GetShopReq) (*Shop, error)
	CreateShop(context.Context, *Shop) (*Shop, error)
	UpdateShop(context.Context, *Shop) (*Shop, error)
	DeleteShop(context.Context, *GetShopReq) (*Empty, error)
}

// UnimplementedMarketplaceCatalogServer can be embedded to have forward compatible implementations.
type UnimplementedMarketplaceCatalogServer struct {
}

func (*UnimplementedMarketplaceCatalogServer) ListProducts(ctx context.Context, req *ListProductsReq) (*ListProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (*UnimplementedMarketplaceCatalogServer) GetProduct(ctx context.Context, req *GetProductReq) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedMarketplaceCatalogServer) CreateProduct(ctx context.Context, req *Product) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (*UnimplementedMarketplaceCatalogServer) UpdateProduct(ctx context.Context, req *Product) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedMarketplaceCatalogServer) DeleteProduct(ctx context.Context, req *GetProductReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedMarketplaceCatalogServer) ListShops(ctx context.Context, req *ListShopsReq) (*ListShopsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShops not implemented")
}
func (*UnimplementedMarketplaceCatalogServer) GetShop(ctx context.Context, req *GetShopReq) (*Shop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShop not implemented")
}
func (*UnimplementedMarketplaceCatalogServer) CreateShop(ctx context.Context, req *Shop) (*Shop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShop not implemented")
}
func (*UnimplementedMarketplaceCatalogServer) UpdateShop(ctx context.Context, req *Shop) (*Shop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShop not implemented")
}
func (*UnimplementedMarketplaceCatalogServer) DeleteShop(ctx context.Context, req *GetShopReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShop not implemented")
}

func RegisterMarketplaceCatalogServer(s *grpc.Server, srv MarketplaceCatalogServer) {
	s.RegisterService(&_MarketplaceCatalog_serviceDesc, srv)
}

func _MarketplaceCatalog_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).ListProducts(ctx, req.(*ListProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceCatalog_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).GetProduct(ctx, req.(*GetProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceCatalog_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).CreateProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceCatalog_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).UpdateProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceCatalog_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).DeleteProduct(ctx, req.(*GetProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceCatalog_ListShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShopsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).ListShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/ListShops",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).ListShops(ctx, req.(*ListShopsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceCatalog_GetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).GetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/GetShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).GetShop(ctx, req.(*GetShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceCatalog_CreateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Shop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).CreateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/CreateShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).CreateShop(ctx, req.(*Shop))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceCatalog_UpdateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Shop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).UpdateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/UpdateShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).UpdateShop(ctx, req.(*Shop))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceCatalog_DeleteShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceCatalogServer).DeleteShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogproto.MarketplaceCatalog/DeleteShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceCatalogServer).DeleteShop(ctx, req.(*GetShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketplaceCatalog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catalogproto.MarketplaceCatalog",
	HandlerType: (*MarketplaceCatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProducts",
			Handler:    _MarketplaceCatalog_ListProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _MarketplaceCatalog_GetProduct_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _MarketplaceCatalog_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _MarketplaceCatalog_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _MarketplaceCatalog_DeleteProduct_Handler,
		},
		{
			MethodName: "ListShops",
			Handler:    _MarketplaceCatalog_ListShops_Handler,
		},
		{
			MethodName: "GetShop",
			Handler:    _MarketplaceCatalog_GetShop_Handler,
		},
		{
			MethodName: "CreateShop",
			Handler:    _MarketplaceCatalog_CreateShop_Handler,
		},
		{
			MethodName: "UpdateShop",
			Handler:    _MarketplaceCatalog_UpdateShop_Handler,
		},
		{
			MethodName: "DeleteShop",
			Handler:    _MarketplaceCatalog_DeleteShop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}
