// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package catalogproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId               int32    `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PricePerKg           int32    `protobuf:"varint,5,opt,name=price_per_kg,json=pricePerKg,proto3" json:"price_per_kg,omitempty"`
	StockKg              float32  `protobuf:"fixed32,6,opt,name=stock_kg,json=stockKg,proto3" json:"stock_kg,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Slug                 string   `protobuf:"bytes,9,opt,name=slug,proto3" json:"slug,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,10,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetShopId() int32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetPricePerKg() int32 {
	if m != nil {
		return m.PricePerKg
	}
	return 0
}

func (m *Product) GetStockKg() float32 {
	if m != nil {
		return m.StockKg
	}
	return 0
}

func (m *Product) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Product) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Product) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Product) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "catalogproto.Product")
}

func init() {
	proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5)
}

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x95, 0xf4, 0x4f, 0x92, 0x53, 0x61, 0xb8, 0x05, 0x03, 0x42, 0x8a, 0x98, 0x32, 0xb1,
	0xf0, 0x04, 0x1d, 0x51, 0x97, 0x2a, 0x12, 0xb3, 0x65, 0x6c, 0xcb, 0xb5, 0x1a, 0x6a, 0xe3, 0x9c,
	0x07, 0x5e, 0x82, 0x67, 0x46, 0xbe, 0x14, 0xb6, 0xfb, 0xbe, 0xcf, 0xc3, 0x4f, 0x86, 0x9b, 0x98,
	0x82, 0xc9, 0x9a, 0x5e, 0x62, 0x0a, 0x14, 0x70, 0xa7, 0x15, 0xa9, 0x29, 0x38, 0xa6, 0xe7, 0x9f,
	0x1a, 0x9a, 0xe3, 0xd2, 0xf1, 0x16, 0x6a, 0x6f, 0x44, 0xd5, 0x57, 0xc3, 0x66, 0xac, 0xbd, 0xc1,
	0x3b, 0x68, 0xe6, 0x53, 0x88, 0xd2, 0x1b, 0x51, 0xb3, 0xdc, 0x16, 0x7c, 0x33, 0x88, 0xb0, 0xbe,
	0xa8, 0x4f, 0x2b, 0x56, 0x7d, 0x35, 0x74, 0x23, 0xdf, 0xf8, 0x00, 0xed, 0x57, 0x56, 0x17, 0xf2,
	0xf4, 0x2d, 0xd6, 0xfc, 0xfa, 0x9f, 0xb1, 0x87, 0x5d, 0x4c, 0x5e, 0x5b, 0x19, 0x6d, 0x92, 0x67,
	0x27, 0x36, 0xdc, 0x81, 0xdd, 0xd1, 0xa6, 0x83, 0xc3, 0x7b, 0x68, 0x67, 0x0a, 0xfa, 0x5c, 0xea,
	0xb6, 0xaf, 0x86, 0x7a, 0x6c, 0x98, 0x0f, 0x0e, 0x9f, 0x00, 0x74, 0xb2, 0x8a, 0xac, 0x91, 0x8a,
	0x44, 0xd3, 0x57, 0xc3, 0x6a, 0xec, 0xae, 0x66, 0x4f, 0x25, 0xe7, 0x68, 0xfe, 0x72, 0xbb, 0xe4,
	0xab, 0xd9, 0x53, 0x99, 0x3a, 0x4f, 0xd9, 0x89, 0x6e, 0x99, 0x5a, 0x6e, 0x7c, 0x84, 0x2e, 0x9e,
	0x02, 0x05, 0x99, 0xd3, 0x24, 0x80, 0x43, 0xcb, 0xe2, 0x3d, 0x4d, 0x1f, 0x5b, 0xfe, 0x97, 0xd7,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0xf8, 0x96, 0xd7, 0x36, 0x01, 0x00, 0x00,
}
