// Code generated by protoc-gen-go. DO NOT EDIT.
// source: review.proto

package catalogproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Review struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            int64    `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId               int64    `protobuf:"varint,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,7,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Rating               float64  `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	CreatedAt            int64    `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_deed8eefad2f709e, []int{0}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Review) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Review) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Review) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *Review) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Review) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Review) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *Review) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Review) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Review) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Review)(nil), "catalogproto.Review")
}

func init() {
	proto.RegisterFile("review.proto", fileDescriptor_deed8eefad2f709e)
}

var fileDescriptor_deed8eefad2f709e = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xd7, 0x4d, 0xb7, 0xc3, 0xe2, 0x21, 0x88, 0x06, 0x44, 0x28, 0x9e, 0x7a, 0xf2,
	0xe2, 0x13, 0xec, 0xb1, 0xd7, 0x82, 0xe7, 0x12, 0x9b, 0xb0, 0x1b, 0x28, 0x9d, 0x30, 0x3b, 0xd5,
	0x97, 0xf0, 0xa1, 0x25, 0xd3, 0xf4, 0xf8, 0x7d, 0x1f, 0x03, 0x3f, 0x03, 0x67, 0x0a, 0x3f, 0x31,
	0xfc, 0x7e, 0x24, 0x42, 0x46, 0x73, 0x9e, 0x1c, 0xbb, 0x19, 0xaf, 0x42, 0xef, 0x7f, 0x15, 0xe8,
	0x41, 0xb2, 0x79, 0x84, 0x2a, 0x7a, 0xab, 0x5a, 0xd5, 0x1d, 0x86, 0x2a, 0x7a, 0xf3, 0x02, 0xf5,
	0x7a, 0x0f, 0x34, 0x46, 0x6f, 0x2b, 0x91, 0x3a, 0x63, 0xef, 0xcd, 0x1b, 0x40, 0x22, 0xf4, 0xeb,
	0xc4, 0xb9, 0x1d, 0xa4, 0x35, 0xc5, 0xf4, 0x72, 0x77, 0xbf, 0x61, 0xca, 0xed, 0x61, 0xbb, 0xcb,
	0xd8, 0x7b, 0xf3, 0x04, 0x47, 0x8e, 0x3c, 0x07, 0x7b, 0x6c, 0x55, 0xd7, 0x0c, 0x1b, 0x18, 0x0b,
	0xf5, 0x84, 0x0b, 0x87, 0x85, 0xad, 0x16, 0xbf, 0xa3, 0x79, 0x85, 0x26, 0xdd, 0x90, 0x71, 0x5c,
	0x69, 0xb6, 0xb5, 0xb4, 0x93, 0x88, 0x2f, 0x9a, 0xcd, 0x33, 0x68, 0x72, 0x1c, 0x97, 0xab, 0x3d,
	0xb5, 0xaa, 0x53, 0x43, 0xa1, 0x3c, 0x6e, 0xa2, 0xe0, 0x38, 0xf8, 0xd1, 0xb1, 0x6d, 0xb6, 0x71,
	0xc5, 0x5c, 0x38, 0xe7, 0x35, 0xf9, 0x3d, 0xc3, 0x96, 0x8b, 0xb9, 0xf0, 0xb7, 0x96, 0xaf, 0x7c,
	0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x38, 0xe9, 0x73, 0x33, 0x01, 0x00, 0x00,
}
