// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop.proto

package catalogproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Shop struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Slug                 string     `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Location             *GPS       `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Products             []*Product `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	CreatedAt            int64      `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64      `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_shop_75fbd773fe1765d2, []int{0}
}
func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (dst *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(dst, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shop) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Shop) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Shop) GetLocation() *GPS {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Shop) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Shop) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Shop) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GPS struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPS) Reset()         { *m = GPS{} }
func (m *GPS) String() string { return proto.CompactTextString(m) }
func (*GPS) ProtoMessage()    {}
func (*GPS) Descriptor() ([]byte, []int) {
	return fileDescriptor_shop_75fbd773fe1765d2, []int{1}
}
func (m *GPS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPS.Unmarshal(m, b)
}
func (m *GPS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPS.Marshal(b, m, deterministic)
}
func (dst *GPS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPS.Merge(dst, src)
}
func (m *GPS) XXX_Size() int {
	return xxx_messageInfo_GPS.Size(m)
}
func (m *GPS) XXX_DiscardUnknown() {
	xxx_messageInfo_GPS.DiscardUnknown(m)
}

var xxx_messageInfo_GPS proto.InternalMessageInfo

func (m *GPS) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GPS) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*Shop)(nil), "catalogproto.Shop")
	proto.RegisterType((*GPS)(nil), "catalogproto.GPS")
}

func init() { proto.RegisterFile("shop.proto", fileDescriptor_shop_75fbd773fe1765d2) }

var fileDescriptor_shop_75fbd773fe1765d2 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x6a, 0xb3, 0x40,
	0x14, 0x85, 0x19, 0x35, 0x89, 0xde, 0xfc, 0x7f, 0xa1, 0x17, 0x0a, 0x43, 0x68, 0x41, 0xb2, 0x72,
	0x53, 0xa1, 0xe9, 0x03, 0x94, 0xac, 0xb2, 0x95, 0xf1, 0x01, 0xca, 0xd4, 0x11, 0x23, 0x4c, 0x9d,
	0xc1, 0xb9, 0xbe, 0x7b, 0x97, 0xc5, 0x19, 0x63, 0xdb, 0xdd, 0x3d, 0xe7, 0xfb, 0x16, 0xe7, 0x02,
	0xb8, 0xab, 0xb1, 0xa5, 0x1d, 0x0d, 0x19, 0xfc, 0xd7, 0x48, 0x92, 0xda, 0x74, 0x3e, 0x1d, 0xfe,
	0xdb, 0xd1, 0xa8, 0xa9, 0xa1, 0x00, 0x8f, 0x5f, 0x0c, 0x92, 0xfa, 0x6a, 0x2c, 0xde, 0x41, 0xd4,
	0x2b, 0xce, 0x72, 0x56, 0x6c, 0x44, 0xd4, 0x2b, 0x44, 0x48, 0x06, 0xf9, 0xd9, 0xf2, 0x28, 0x67,
	0x45, 0x26, 0xfc, 0x8d, 0x1c, 0x76, 0x52, 0xa9, 0xb1, 0x75, 0x8e, 0xc7, 0xbe, 0xbe, 0xc5, 0xd9,
	0x76, 0x7a, 0xea, 0x78, 0x12, 0xec, 0xf9, 0xc6, 0x67, 0x48, 0xb5, 0x69, 0x24, 0xf5, 0x66, 0xe0,
	0x9b, 0x9c, 0x15, 0xfb, 0xd3, 0x7d, 0xf9, 0x7b, 0x4a, 0x79, 0xa9, 0x6a, 0xb1, 0x2a, 0xf8, 0x02,
	0xe9, 0x32, 0xcd, 0xf1, 0x6d, 0x1e, 0x17, 0xfb, 0xd3, 0xc3, 0x5f, 0xbd, 0x0a, 0x54, 0xac, 0x1a,
	0x3e, 0x01, 0x34, 0x63, 0x2b, 0xa9, 0x55, 0xef, 0x92, 0xf8, 0x2e, 0x67, 0x45, 0x2c, 0xb2, 0xa5,
	0x39, 0xd3, 0x8c, 0x27, 0xab, 0x6e, 0x38, 0x0d, 0x78, 0x69, 0xce, 0x74, 0x7c, 0x83, 0xf8, 0x52,
	0xd5, 0x78, 0x80, 0x54, 0x4b, 0xea, 0x69, 0x52, 0xad, 0x7f, 0x9f, 0x89, 0x35, 0xe3, 0x23, 0x64,
	0xda, 0x0c, 0x5d, 0x80, 0x91, 0x87, 0x3f, 0xc5, 0xc7, 0xd6, 0xef, 0x7a, 0xfd, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x04, 0x63, 0x56, 0x73, 0x6d, 0x01, 0x00, 0x00,
}
