// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/idzharbae/marketplace-backend/svc/transaction/internal (interfaces: OrderUC)

// Package ucmock is a generated GoMock package.
package ucmock

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/idzharbae/marketplace-backend/svc/transaction/internal/entity"
	request "github.com/idzharbae/marketplace-backend/svc/transaction/internal/request"
	reflect "reflect"
)

// MockOrderUC is a mock of OrderUC interface.
type MockOrderUC struct {
	ctrl     *gomock.Controller
	recorder *MockOrderUCMockRecorder
}

// MockOrderUCMockRecorder is the mock recorder for MockOrderUC.
type MockOrderUCMockRecorder struct {
	mock *MockOrderUC
}

// NewMockOrderUC creates a new mock instance.
func NewMockOrderUC(ctrl *gomock.Controller) *MockOrderUC {
	mock := &MockOrderUC{ctrl: ctrl}
	mock.recorder = &MockOrderUCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderUC) EXPECT() *MockOrderUCMockRecorder {
	return m.recorder
}

// CreateFromCarts mocks base method.
func (m *MockOrderUC) CreateFromCarts(arg0 request.CheckoutReq) ([]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromCarts", arg0)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFromCarts indicates an expected call of CreateFromCarts.
func (mr *MockOrderUCMockRecorder) CreateFromCarts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromCarts", reflect.TypeOf((*MockOrderUC)(nil).CreateFromCarts), arg0)
}

// Fulfill mocks base method.
func (m *MockOrderUC) Fulfill(arg0 entity.Order) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fulfill", arg0)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fulfill indicates an expected call of Fulfill.
func (mr *MockOrderUCMockRecorder) Fulfill(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fulfill", reflect.TypeOf((*MockOrderUC)(nil).Fulfill), arg0)
}

// Get mocks base method.
func (m *MockOrderUC) Get(arg0 entity.Order) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrderUCMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderUC)(nil).Get), arg0)
}

// List mocks base method.
func (m *MockOrderUC) List(arg0 request.ListOrderReq) ([]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrderUCMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrderUC)(nil).List), arg0)
}

// UpdateOrderStatusToOnShipment mocks base method.
func (m *MockOrderUC) UpdateOrderStatusToOnShipment(arg0, arg1 int64) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatusToOnShipment", arg0, arg1)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatusToOnShipment indicates an expected call of UpdateOrderStatusToOnShipment.
func (mr *MockOrderUCMockRecorder) UpdateOrderStatusToOnShipment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusToOnShipment", reflect.TypeOf((*MockOrderUC)(nil).UpdateOrderStatusToOnShipment), arg0, arg1)
}
