// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package prototransaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64      `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalPrice           int64      `protobuf:"varint,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Products             []*Product `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	Status               int32      `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Payment              *Payment   `protobuf:"bytes,6,opt,name=payment,proto3" json:"payment,omitempty"`
	ShopId               int64      `protobuf:"varint,7,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Order) GetTotalPrice() int64 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Order) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *Order) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func init() {
	proto.RegisterType((*Order)(nil), "prototransaction.Order")
}

func init() {
	proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077)
}

var fileDescriptor_cd01338c35d87077 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8e, 0xcd, 0x4e, 0xc4, 0x20,
	0x14, 0x85, 0x43, 0x6b, 0xa9, 0xb9, 0xcd, 0x18, 0xc3, 0x42, 0x71, 0x36, 0x12, 0x57, 0x5d, 0x75,
	0xe1, 0xc4, 0x87, 0x98, 0x95, 0x0d, 0x2f, 0xd0, 0x60, 0x21, 0x91, 0x44, 0x0b, 0x81, 0xdb, 0x85,
	0x2f, 0xed, 0x33, 0x18, 0x7e, 0x74, 0x61, 0x32, 0x2b, 0x72, 0x0e, 0xdf, 0x81, 0x0f, 0x06, 0x17,
	0xb4, 0x09, 0x93, 0x0f, 0x0e, 0x1d, 0xbb, 0xcd, 0x07, 0x06, 0xb5, 0x45, 0xb5, 0xa2, 0x75, 0xdb,
	0xf1, 0xe0, 0x83, 0xd3, 0xfb, 0x8a, 0x05, 0x38, 0x1e, 0xbc, 0xfa, 0xfa, 0x34, 0x5b, 0x8d, 0x4f,
	0xdf, 0x04, 0xba, 0xd7, 0xb4, 0x67, 0x37, 0xd0, 0x58, 0xcd, 0x89, 0x20, 0x63, 0x2b, 0x1b, 0xab,
	0xd9, 0x3d, 0xf4, 0x7b, 0x34, 0x61, 0xb1, 0x9a, 0x37, 0xb9, 0xa4, 0x29, 0x9e, 0x35, 0x7b, 0x84,
	0x01, 0x1d, 0xaa, 0x8f, 0xc5, 0x07, 0xbb, 0x1a, 0xde, 0xe6, 0x4b, 0xc8, 0xd5, 0x9c, 0x1a, 0xf6,
	0x02, 0xd7, 0xf5, 0xcf, 0xc8, 0xaf, 0x44, 0x3b, 0x0e, 0xcf, 0x0f, 0xd3, 0x7f, 0xad, 0x69, 0x2e,
	0x84, 0xfc, 0x43, 0xd9, 0x1d, 0xd0, 0x88, 0x0a, 0xf7, 0xc8, 0x3b, 0x41, 0xc6, 0x4e, 0xd6, 0xc4,
	0x4e, 0xd0, 0x57, 0x67, 0x4e, 0x05, 0xb9, 0xf0, 0x5a, 0x01, 0xe4, 0x2f, 0x99, 0xec, 0xe3, 0xbb,
	0xf3, 0xc9, 0xbe, 0x2f, 0xf6, 0x29, 0x9e, 0xf5, 0x1b, 0xcd, 0xdb, 0xd3, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x79, 0x3c, 0x8f, 0xf9, 0x36, 0x01, 0x00, 0x00,
}
