// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package prototransaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId               int64    `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AmountKg             int32    `protobuf:"varint,4,opt,name=amount_kg,json=amountKg,proto3" json:"amount_kg,omitempty"`
	PricePerKg           int32    `protobuf:"varint,5,opt,name=price_per_kg,json=pricePerKg,proto3" json:"price_per_kg,omitempty"`
	TotalPrice           int64    `protobuf:"varint,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetAmountKg() int32 {
	if m != nil {
		return m.AmountKg
	}
	return 0
}

func (m *Product) GetPricePerKg() int32 {
	if m != nil {
		return m.PricePerKg
	}
	return 0
}

func (m *Product) GetTotalPrice() int64 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*Product)(nil), "prototransaction.Product")
}

func init() {
	proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5)
}

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0xce, 0x3d, 0xaa, 0xc3, 0x30,
	0x0c, 0x07, 0x70, 0x9c, 0xcf, 0x17, 0xbd, 0x0f, 0x1e, 0x5a, 0x6a, 0xe8, 0x50, 0xd3, 0x29, 0x53,
	0x97, 0x9e, 0xa2, 0x64, 0x09, 0xb9, 0x80, 0x71, 0x63, 0x93, 0x9a, 0x36, 0xb6, 0x71, 0x9c, 0x2b,
	0xf5, 0x9c, 0x25, 0xca, 0x24, 0xe9, 0xf7, 0x17, 0x48, 0xf0, 0x1b, 0xa2, 0xd7, 0xeb, 0x98, 0x2e,
	0x21, 0xfa, 0xe4, 0xf1, 0x9f, 0x4a, 0x8a, 0xca, 0x2d, 0x6a, 0x4c, 0xd6, 0xbb, 0xf3, 0x9b, 0x41,
	0xdd, 0xef, 0x3b, 0xf8, 0x07, 0x99, 0xd5, 0x9c, 0x09, 0xd6, 0xe6, 0x43, 0x66, 0x35, 0x1e, 0xa0,
	0x5e, 0x1e, 0x3e, 0x48, 0xab, 0x79, 0x46, 0x58, 0x6d, 0xe3, 0x4d, 0x23, 0x42, 0xe1, 0xd4, 0x6c,
	0x78, 0x2e, 0x58, 0xdb, 0x0c, 0xd4, 0xe3, 0x11, 0x1a, 0x35, 0xfb, 0xd5, 0x25, 0xf9, 0x9c, 0x78,
	0x21, 0x58, 0x5b, 0x0e, 0x5f, 0x3b, 0x74, 0x13, 0x0a, 0xf8, 0x09, 0xd1, 0x8e, 0x46, 0x06, 0x13,
	0xb7, 0xbc, 0xa4, 0x1c, 0xc8, 0x7a, 0x13, 0xbb, 0x09, 0x4f, 0xf0, 0x9d, 0x7c, 0x52, 0x2f, 0x49,
	0xc6, 0x2b, 0xba, 0x07, 0x44, 0xfd, 0x26, 0xf7, 0x8a, 0x5e, 0xbf, 0x7e, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x60, 0x68, 0xc9, 0x33, 0xd2, 0x00, 0x00, 0x00,
}
