// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package prototransaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShipProductReq struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShopId               int64    `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipProductReq) Reset()         { *m = ShipProductReq{} }
func (m *ShipProductReq) String() string { return proto.CompactTextString(m) }
func (*ShipProductReq) ProtoMessage()    {}
func (*ShipProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *ShipProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipProductReq.Unmarshal(m, b)
}
func (m *ShipProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipProductReq.Marshal(b, m, deterministic)
}
func (m *ShipProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipProductReq.Merge(m, src)
}
func (m *ShipProductReq) XXX_Size() int {
	return xxx_messageInfo_ShipProductReq.Size(m)
}
func (m *ShipProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShipProductReq proto.InternalMessageInfo

func (m *ShipProductReq) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *ShipProductReq) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type ShipProductResp struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipProductResp) Reset()         { *m = ShipProductResp{} }
func (m *ShipProductResp) String() string { return proto.CompactTextString(m) }
func (*ShipProductResp) ProtoMessage()    {}
func (*ShipProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *ShipProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipProductResp.Unmarshal(m, b)
}
func (m *ShipProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipProductResp.Marshal(b, m, deterministic)
}
func (m *ShipProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipProductResp.Merge(m, src)
}
func (m *ShipProductResp) XXX_Size() int {
	return xxx_messageInfo_ShipProductResp.Size(m)
}
func (m *ShipProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_ShipProductResp proto.InternalMessageInfo

func (m *ShipProductResp) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ListOrderReq struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ShopId               int64    `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderReq) Reset()         { *m = ListOrderReq{} }
func (m *ListOrderReq) String() string { return proto.CompactTextString(m) }
func (*ListOrderReq) ProtoMessage()    {}
func (*ListOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *ListOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderReq.Unmarshal(m, b)
}
func (m *ListOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderReq.Marshal(b, m, deterministic)
}
func (m *ListOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderReq.Merge(m, src)
}
func (m *ListOrderReq) XXX_Size() int {
	return xxx_messageInfo_ListOrderReq.Size(m)
}
func (m *ListOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderReq proto.InternalMessageInfo

func (m *ListOrderReq) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *ListOrderReq) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type ListOrderResp struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderResp) Reset()         { *m = ListOrderResp{} }
func (m *ListOrderResp) String() string { return proto.CompactTextString(m) }
func (*ListOrderResp) ProtoMessage()    {}
func (*ListOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *ListOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderResp.Unmarshal(m, b)
}
func (m *ListOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderResp.Marshal(b, m, deterministic)
}
func (m *ListOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderResp.Merge(m, src)
}
func (m *ListOrderResp) XXX_Size() int {
	return xxx_messageInfo_ListOrderResp.Size(m)
}
func (m *ListOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderResp proto.InternalMessageInfo

func (m *ListOrderResp) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type GetOrderReq struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId           int64    `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ShopId               int64    `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderReq) Reset()         { *m = GetOrderReq{} }
func (m *GetOrderReq) String() string { return proto.CompactTextString(m) }
func (*GetOrderReq) ProtoMessage()    {}
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *GetOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderReq.Unmarshal(m, b)
}
func (m *GetOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderReq.Marshal(b, m, deterministic)
}
func (m *GetOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderReq.Merge(m, src)
}
func (m *GetOrderReq) XXX_Size() int {
	return xxx_messageInfo_GetOrderReq.Size(m)
}
func (m *GetOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderReq proto.InternalMessageInfo

func (m *GetOrderReq) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *GetOrderReq) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *GetOrderReq) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetOrderResp struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResp) Reset()         { *m = GetOrderResp{} }
func (m *GetOrderResp) String() string { return proto.CompactTextString(m) }
func (*GetOrderResp) ProtoMessage()    {}
func (*GetOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}

func (m *GetOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResp.Unmarshal(m, b)
}
func (m *GetOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResp.Marshal(b, m, deterministic)
}
func (m *GetOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResp.Merge(m, src)
}
func (m *GetOrderResp) XXX_Size() int {
	return xxx_messageInfo_GetOrderResp.Size(m)
}
func (m *GetOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResp proto.InternalMessageInfo

func (m *GetOrderResp) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ListCartItemsReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCartItemsReq) Reset()         { *m = ListCartItemsReq{} }
func (m *ListCartItemsReq) String() string { return proto.CompactTextString(m) }
func (*ListCartItemsReq) ProtoMessage()    {}
func (*ListCartItemsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{6}
}

func (m *ListCartItemsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCartItemsReq.Unmarshal(m, b)
}
func (m *ListCartItemsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCartItemsReq.Marshal(b, m, deterministic)
}
func (m *ListCartItemsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCartItemsReq.Merge(m, src)
}
func (m *ListCartItemsReq) XXX_Size() int {
	return xxx_messageInfo_ListCartItemsReq.Size(m)
}
func (m *ListCartItemsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCartItemsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListCartItemsReq proto.InternalMessageInfo

func (m *ListCartItemsReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListCartItemsResp struct {
	Cart                 []*Cart  `protobuf:"bytes,1,rep,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCartItemsResp) Reset()         { *m = ListCartItemsResp{} }
func (m *ListCartItemsResp) String() string { return proto.CompactTextString(m) }
func (*ListCartItemsResp) ProtoMessage()    {}
func (*ListCartItemsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{7}
}

func (m *ListCartItemsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCartItemsResp.Unmarshal(m, b)
}
func (m *ListCartItemsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCartItemsResp.Marshal(b, m, deterministic)
}
func (m *ListCartItemsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCartItemsResp.Merge(m, src)
}
func (m *ListCartItemsResp) XXX_Size() int {
	return xxx_messageInfo_ListCartItemsResp.Size(m)
}
func (m *ListCartItemsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCartItemsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListCartItemsResp proto.InternalMessageInfo

func (m *ListCartItemsResp) GetCart() []*Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type UpdateCartReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuantityKg           float64  `protobuf:"fixed64,3,opt,name=quantity_kg,json=quantityKg,proto3" json:"quantity_kg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCartReq) Reset()         { *m = UpdateCartReq{} }
func (m *UpdateCartReq) String() string { return proto.CompactTextString(m) }
func (*UpdateCartReq) ProtoMessage()    {}
func (*UpdateCartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{8}
}

func (m *UpdateCartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCartReq.Unmarshal(m, b)
}
func (m *UpdateCartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCartReq.Marshal(b, m, deterministic)
}
func (m *UpdateCartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCartReq.Merge(m, src)
}
func (m *UpdateCartReq) XXX_Size() int {
	return xxx_messageInfo_UpdateCartReq.Size(m)
}
func (m *UpdateCartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCartReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCartReq proto.InternalMessageInfo

func (m *UpdateCartReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateCartReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateCartReq) GetQuantityKg() float64 {
	if m != nil {
		return m.QuantityKg
	}
	return 0
}

type AddToCartReq struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuantityKg           float64  `protobuf:"fixed64,3,opt,name=quantity_kg,json=quantityKg,proto3" json:"quantity_kg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToCartReq) Reset()         { *m = AddToCartReq{} }
func (m *AddToCartReq) String() string { return proto.CompactTextString(m) }
func (*AddToCartReq) ProtoMessage()    {}
func (*AddToCartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{9}
}

func (m *AddToCartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToCartReq.Unmarshal(m, b)
}
func (m *AddToCartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToCartReq.Marshal(b, m, deterministic)
}
func (m *AddToCartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToCartReq.Merge(m, src)
}
func (m *AddToCartReq) XXX_Size() int {
	return xxx_messageInfo_AddToCartReq.Size(m)
}
func (m *AddToCartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToCartReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddToCartReq proto.InternalMessageInfo

func (m *AddToCartReq) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *AddToCartReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddToCartReq) GetQuantityKg() float64 {
	if m != nil {
		return m.QuantityKg
	}
	return 0
}

type RemoveCartReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveCartReq) Reset()         { *m = RemoveCartReq{} }
func (m *RemoveCartReq) String() string { return proto.CompactTextString(m) }
func (*RemoveCartReq) ProtoMessage()    {}
func (*RemoveCartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{10}
}

func (m *RemoveCartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveCartReq.Unmarshal(m, b)
}
func (m *RemoveCartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveCartReq.Marshal(b, m, deterministic)
}
func (m *RemoveCartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveCartReq.Merge(m, src)
}
func (m *RemoveCartReq) XXX_Size() int {
	return xxx_messageInfo_RemoveCartReq.Size(m)
}
func (m *RemoveCartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveCartReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveCartReq proto.InternalMessageInfo

func (m *RemoveCartReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RemoveCartReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RemoveCartResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveCartResp) Reset()         { *m = RemoveCartResp{} }
func (m *RemoveCartResp) String() string { return proto.CompactTextString(m) }
func (*RemoveCartResp) ProtoMessage()    {}
func (*RemoveCartResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{11}
}

func (m *RemoveCartResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveCartResp.Unmarshal(m, b)
}
func (m *RemoveCartResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveCartResp.Marshal(b, m, deterministic)
}
func (m *RemoveCartResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveCartResp.Merge(m, src)
}
func (m *RemoveCartResp) XXX_Size() int {
	return xxx_messageInfo_RemoveCartResp.Size(m)
}
func (m *RemoveCartResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveCartResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveCartResp proto.InternalMessageInfo

func (m *RemoveCartResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CheckoutReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CartIds              []int64  `protobuf:"varint,2,rep,packed,name=cart_ids,json=cartIds,proto3" json:"cart_ids,omitempty"`
	PaymentAmount        int64    `protobuf:"varint,3,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutReq) Reset()         { *m = CheckoutReq{} }
func (m *CheckoutReq) String() string { return proto.CompactTextString(m) }
func (*CheckoutReq) ProtoMessage()    {}
func (*CheckoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{12}
}

func (m *CheckoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutReq.Unmarshal(m, b)
}
func (m *CheckoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutReq.Marshal(b, m, deterministic)
}
func (m *CheckoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutReq.Merge(m, src)
}
func (m *CheckoutReq) XXX_Size() int {
	return xxx_messageInfo_CheckoutReq.Size(m)
}
func (m *CheckoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutReq proto.InternalMessageInfo

func (m *CheckoutReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CheckoutReq) GetCartIds() []int64 {
	if m != nil {
		return m.CartIds
	}
	return nil
}

func (m *CheckoutReq) GetPaymentAmount() int64 {
	if m != nil {
		return m.PaymentAmount
	}
	return 0
}

type CheckoutResp struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutResp) Reset()         { *m = CheckoutResp{} }
func (m *CheckoutResp) String() string { return proto.CompactTextString(m) }
func (*CheckoutResp) ProtoMessage()    {}
func (*CheckoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{13}
}

func (m *CheckoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutResp.Unmarshal(m, b)
}
func (m *CheckoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutResp.Marshal(b, m, deterministic)
}
func (m *CheckoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutResp.Merge(m, src)
}
func (m *CheckoutResp) XXX_Size() int {
	return xxx_messageInfo_CheckoutResp.Size(m)
}
func (m *CheckoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutResp proto.InternalMessageInfo

func (m *CheckoutResp) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type FulfillReq struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FulfillReq) Reset()         { *m = FulfillReq{} }
func (m *FulfillReq) String() string { return proto.CompactTextString(m) }
func (*FulfillReq) ProtoMessage()    {}
func (*FulfillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{14}
}

func (m *FulfillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FulfillReq.Unmarshal(m, b)
}
func (m *FulfillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FulfillReq.Marshal(b, m, deterministic)
}
func (m *FulfillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FulfillReq.Merge(m, src)
}
func (m *FulfillReq) XXX_Size() int {
	return xxx_messageInfo_FulfillReq.Size(m)
}
func (m *FulfillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FulfillReq.DiscardUnknown(m)
}

var xxx_messageInfo_FulfillReq proto.InternalMessageInfo

func (m *FulfillReq) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *FulfillReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type FulfillResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FulfillResp) Reset()         { *m = FulfillResp{} }
func (m *FulfillResp) String() string { return proto.CompactTextString(m) }
func (*FulfillResp) ProtoMessage()    {}
func (*FulfillResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{15}
}

func (m *FulfillResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FulfillResp.Unmarshal(m, b)
}
func (m *FulfillResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FulfillResp.Marshal(b, m, deterministic)
}
func (m *FulfillResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FulfillResp.Merge(m, src)
}
func (m *FulfillResp) XXX_Size() int {
	return xxx_messageInfo_FulfillResp.Size(m)
}
func (m *FulfillResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FulfillResp.DiscardUnknown(m)
}

var xxx_messageInfo_FulfillResp proto.InternalMessageInfo

func (m *FulfillResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*ShipProductReq)(nil), "prototransaction.ShipProductReq")
	proto.RegisterType((*ShipProductResp)(nil), "prototransaction.ShipProductResp")
	proto.RegisterType((*ListOrderReq)(nil), "prototransaction.ListOrderReq")
	proto.RegisterType((*ListOrderResp)(nil), "prototransaction.ListOrderResp")
	proto.RegisterType((*GetOrderReq)(nil), "prototransaction.GetOrderReq")
	proto.RegisterType((*GetOrderResp)(nil), "prototransaction.GetOrderResp")
	proto.RegisterType((*ListCartItemsReq)(nil), "prototransaction.ListCartItemsReq")
	proto.RegisterType((*ListCartItemsResp)(nil), "prototransaction.ListCartItemsResp")
	proto.RegisterType((*UpdateCartReq)(nil), "prototransaction.UpdateCartReq")
	proto.RegisterType((*AddToCartReq)(nil), "prototransaction.AddToCartReq")
	proto.RegisterType((*RemoveCartReq)(nil), "prototransaction.RemoveCartReq")
	proto.RegisterType((*RemoveCartResp)(nil), "prototransaction.RemoveCartResp")
	proto.RegisterType((*CheckoutReq)(nil), "prototransaction.CheckoutReq")
	proto.RegisterType((*CheckoutResp)(nil), "prototransaction.CheckoutResp")
	proto.RegisterType((*FulfillReq)(nil), "prototransaction.FulfillReq")
	proto.RegisterType((*FulfillResp)(nil), "prototransaction.FulfillResp")
}

func init() {
	proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490)
}

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x51, 0x53, 0xd3, 0x40,
	0x10, 0xa6, 0xad, 0xb4, 0xb0, 0x69, 0x2b, 0xdc, 0x03, 0xd4, 0x8c, 0x85, 0x7a, 0x8e, 0xa3, 0x83,
	0x23, 0xce, 0xe0, 0x8b, 0x2f, 0x0e, 0x30, 0xa8, 0x90, 0x41, 0x45, 0x03, 0x3e, 0xe8, 0x4b, 0x27,
	0xe4, 0x0e, 0x9a, 0xa1, 0xcd, 0x5d, 0x73, 0x17, 0x67, 0xf8, 0xdd, 0xfe, 0x01, 0xe7, 0x2e, 0x49,
	0x73, 0x6d, 0x62, 0x18, 0xf4, 0x09, 0x6e, 0xf7, 0xbb, 0x6f, 0xbf, 0xdd, 0x7e, 0x7b, 0x81, 0x75,
	0x19, 0x79, 0xa1, 0xf0, 0x7c, 0x19, 0xb0, 0x70, 0x97, 0x47, 0x4c, 0x32, 0xb4, 0xa6, 0xff, 0x18,
	0x71, 0xdb, 0x62, 0x11, 0xa1, 0x51, 0x92, 0xb6, 0xc1, 0xf7, 0x22, 0x99, 0xfc, 0x8f, 0xdf, 0x43,
	0xf7, 0x7c, 0x14, 0xf0, 0xaf, 0x11, 0x23, 0xb1, 0x2f, 0x5d, 0x3a, 0x45, 0x8f, 0x60, 0x45, 0x83,
	0x87, 0x01, 0xe9, 0xd5, 0x06, 0xb5, 0x17, 0x0d, 0xb7, 0xa5, 0xcf, 0x0e, 0x41, 0x9b, 0xd0, 0x12,
	0x23, 0xc6, 0x55, 0xa6, 0xae, 0x33, 0x4d, 0x75, 0x74, 0x08, 0x3e, 0x80, 0x87, 0x73, 0x2c, 0x82,
	0xa3, 0x57, 0xb0, 0xac, 0xaf, 0x69, 0x0e, 0x6b, 0x6f, 0x73, 0x77, 0x51, 0xd3, 0xee, 0x99, 0x4a,
	0xbb, 0x09, 0x0a, 0x9f, 0x40, 0xfb, 0x53, 0x20, 0x64, 0x12, 0xa3, 0x53, 0xb4, 0x0d, 0x96, 0x1f,
	0x0b, 0xc9, 0x26, 0xa6, 0x10, 0xc8, 0x42, 0xd5, 0x5a, 0x3a, 0x06, 0x93, 0xe0, 0xe8, 0x35, 0x34,
	0x75, 0x0d, 0xd1, 0xab, 0x0d, 0x1a, 0x55, 0x52, 0x52, 0x18, 0xbe, 0x04, 0xeb, 0x98, 0xe6, 0x52,
	0x2a, 0x06, 0xb2, 0xa0, 0xb2, 0x5e, 0xa5, 0xb2, 0x31, 0xa7, 0xf2, 0x1d, 0xb4, 0xf3, 0x1a, 0xf7,
	0x1f, 0xd7, 0x4b, 0x58, 0x53, 0x4d, 0x1e, 0x79, 0x91, 0x74, 0x24, 0x9d, 0x08, 0xa5, 0x73, 0x13,
	0x5a, 0xb1, 0x30, 0x65, 0x36, 0xd5, 0xd1, 0x21, 0x78, 0x1f, 0xd6, 0x17, 0xc0, 0x82, 0xa3, 0x1d,
	0x78, 0xa0, 0x6c, 0x90, 0xce, 0x64, 0xa3, 0x58, 0x4f, 0xc1, 0x5d, 0x8d, 0xc1, 0x3f, 0xa0, 0xf3,
	0x9d, 0x13, 0x4f, 0x52, 0x1d, 0xa3, 0x53, 0xd4, 0x85, 0xfa, 0xac, 0x4a, 0x3d, 0x20, 0x66, 0xe9,
	0xba, 0x59, 0x5a, 0x0d, 0x68, 0x1a, 0x7b, 0xa1, 0x0c, 0xe4, 0xed, 0xf0, 0xe6, 0x5a, 0xcf, 0xa0,
	0xe6, 0x42, 0x16, 0x3a, 0xbd, 0xc6, 0xd7, 0xd0, 0x3e, 0x24, 0xe4, 0x82, 0x65, 0xcc, 0x7d, 0x00,
	0x9e, 0xb8, 0x28, 0xef, 0x63, 0x35, 0x8d, 0x38, 0xff, 0x53, 0xe8, 0x2d, 0x74, 0x5c, 0x3a, 0x61,
	0xbf, 0xee, 0xdd, 0x03, 0xde, 0x81, 0xae, 0x79, 0x53, 0x70, 0xd4, 0x83, 0x96, 0x88, 0x7d, 0x9f,
	0x0a, 0xa1, 0xef, 0xaf, 0xb8, 0xd9, 0x11, 0x8f, 0xc0, 0x3a, 0x1a, 0x51, 0xff, 0x86, 0xc5, 0xb2,
	0xea, 0x27, 0x51, 0x9e, 0x52, 0x93, 0x1d, 0x06, 0x44, 0xf4, 0xea, 0x83, 0x86, 0xf2, 0x94, 0x3a,
	0x3b, 0x44, 0xa0, 0x67, 0xd0, 0xe5, 0xde, 0xed, 0x84, 0x86, 0x72, 0xe8, 0x4d, 0x58, 0x1c, 0xca,
	0xd4, 0x39, 0x9d, 0x34, 0x7a, 0xa8, 0x83, 0x78, 0x1f, 0xda, 0x79, 0xa5, 0x7f, 0x71, 0xf9, 0x01,
	0xc0, 0xc7, 0x78, 0x7c, 0x15, 0x8c, 0xc7, 0x77, 0x6f, 0x7d, 0xf9, 0x60, 0x9e, 0x83, 0x35, 0x63,
	0xa8, 0x9a, 0xca, 0xde, 0xef, 0x65, 0xd8, 0xf8, 0xec, 0x45, 0x37, 0x54, 0xf2, 0xb1, 0xe7, 0xd3,
	0x8b, 0x5c, 0x13, 0xfa, 0x99, 0x6c, 0xeb, 0xcc, 0x9b, 0x08, 0x17, 0x75, 0x2f, 0x3a, 0xdd, 0x7e,
	0x7a, 0x27, 0x46, 0x70, 0xbc, 0x84, 0x3e, 0xc0, 0xea, 0xcc, 0x5b, 0x68, 0xab, 0x78, 0xc7, 0x34,
	0x9e, 0xfd, 0x97, 0x0d, 0xc0, 0x4b, 0xe8, 0x18, 0x20, 0x77, 0x3f, 0xda, 0x2e, 0xe2, 0xe6, 0x76,
	0xa3, 0x82, 0xe8, 0x1b, 0x40, 0x6e, 0xa4, 0x32, 0xa2, 0x39, 0x83, 0xda, 0x83, 0x6a, 0x80, 0x6e,
	0xf1, 0x0b, 0xac, 0xce, 0x1e, 0xbb, 0xb2, 0x16, 0xcd, 0x37, 0xd5, 0xde, 0xae, 0xcc, 0x6b, 0xbe,
	0x53, 0x58, 0xc9, 0x9e, 0x25, 0xd4, 0x2f, 0xc2, 0x8d, 0x67, 0xd1, 0xde, 0xaa, 0x4a, 0x67, 0x64,
	0x99, 0x45, 0xcb, 0xc8, 0x8c, 0x45, 0x29, 0x23, 0x33, 0xdd, 0x8d, 0x97, 0xd0, 0x15, 0xf4, 0x93,
	0x39, 0xeb, 0x0a, 0xe7, 0xd2, 0x93, 0xb1, 0xb8, 0x60, 0x67, 0xa1, 0xfa, 0xee, 0xa8, 0xb5, 0x40,
	0x25, 0xe3, 0x9a, 0xff, 0xb2, 0xd9, 0x4f, 0xee, 0x40, 0xe8, 0x3a, 0x27, 0xd0, 0x4a, 0x4d, 0x8d,
	0x1e, 0x17, 0xf1, 0xf9, 0xc6, 0xd8, 0xfd, 0x8a, 0xac, 0x62, 0xba, 0x6c, 0xea, 0xfc, 0x9b, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x87, 0x51, 0xb3, 0xa1, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MarketplaceTransactionClient is the client API for MarketplaceTransaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketplaceTransactionClient interface {
	// Cart
	ListCartItems(ctx context.Context, in *ListCartItemsReq, opts ...grpc.CallOption) (*ListCartItemsResp, error)
	AddToCart(ctx context.Context, in *AddToCartReq, opts ...grpc.CallOption) (*Cart, error)
	UpdateCart(ctx context.Context, in *UpdateCartReq, opts ...grpc.CallOption) (*Cart, error)
	RemoveCart(ctx context.Context, in *RemoveCartReq, opts ...grpc.CallOption) (*RemoveCartResp, error)
	// Order
	ListOrder(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderResp, error)
	GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
	Checkout(ctx context.Context, in *CheckoutReq, opts ...grpc.CallOption) (*CheckoutResp, error)
	UpdateOrderStatusToOnShipment(ctx context.Context, in *ShipProductReq, opts ...grpc.CallOption) (*ShipProductResp, error)
	Fulfill(ctx context.Context, in *FulfillReq, opts ...grpc.CallOption) (*FulfillResp, error)
}

type marketplaceTransactionClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketplaceTransactionClient(cc grpc.ClientConnInterface) MarketplaceTransactionClient {
	return &marketplaceTransactionClient{cc}
}

func (c *marketplaceTransactionClient) ListCartItems(ctx context.Context, in *ListCartItemsReq, opts ...grpc.CallOption) (*ListCartItemsResp, error) {
	out := new(ListCartItemsResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/ListCartItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) AddToCart(ctx context.Context, in *AddToCartReq, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/AddToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) UpdateCart(ctx context.Context, in *UpdateCartReq, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/UpdateCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) RemoveCart(ctx context.Context, in *RemoveCartReq, opts ...grpc.CallOption) (*RemoveCartResp, error) {
	out := new(RemoveCartResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/RemoveCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) ListOrder(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderResp, error) {
	out := new(ListOrderResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/ListOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	out := new(GetOrderResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) Checkout(ctx context.Context, in *CheckoutReq, opts ...grpc.CallOption) (*CheckoutResp, error) {
	out := new(CheckoutResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/Checkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) UpdateOrderStatusToOnShipment(ctx context.Context, in *ShipProductReq, opts ...grpc.CallOption) (*ShipProductResp, error) {
	out := new(ShipProductResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/UpdateOrderStatusToOnShipment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) Fulfill(ctx context.Context, in *FulfillReq, opts ...grpc.CallOption) (*FulfillResp, error) {
	out := new(FulfillResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/Fulfill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketplaceTransactionServer is the server API for MarketplaceTransaction service.
type MarketplaceTransactionServer interface {
	// Cart
	ListCartItems(context.Context, *ListCartItemsReq) (*ListCartItemsResp, error)
	AddToCart(context.Context, *AddToCartReq) (*Cart, error)
	UpdateCart(context.Context, *UpdateCartReq) (*Cart, error)
	RemoveCart(context.Context, *RemoveCartReq) (*RemoveCartResp, error)
	// Order
	ListOrder(context.Context, *ListOrderReq) (*ListOrderResp, error)
	GetOrder(context.Context, *GetOrderReq) (*GetOrderResp, error)
	Checkout(context.Context, *CheckoutReq) (*CheckoutResp, error)
	UpdateOrderStatusToOnShipment(context.Context, *ShipProductReq) (*ShipProductResp, error)
	Fulfill(context.Context, *FulfillReq) (*FulfillResp, error)
}

// UnimplementedMarketplaceTransactionServer can be embedded to have forward compatible implementations.
type UnimplementedMarketplaceTransactionServer struct {
}

func (*UnimplementedMarketplaceTransactionServer) ListCartItems(ctx context.Context, req *ListCartItemsReq) (*ListCartItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCartItems not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) AddToCart(ctx context.Context, req *AddToCartReq) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) UpdateCart(ctx context.Context, req *UpdateCartReq) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCart not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) RemoveCart(ctx context.Context, req *RemoveCartReq) (*RemoveCartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCart not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) ListOrder(ctx context.Context, req *ListOrderReq) (*ListOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrder not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) GetOrder(ctx context.Context, req *GetOrderReq) (*GetOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) Checkout(ctx context.Context, req *CheckoutReq) (*CheckoutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkout not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) UpdateOrderStatusToOnShipment(ctx context.Context, req *ShipProductReq) (*ShipProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderStatusToOnShipment not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) Fulfill(ctx context.Context, req *FulfillReq) (*FulfillResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fulfill not implemented")
}

func RegisterMarketplaceTransactionServer(s *grpc.Server, srv MarketplaceTransactionServer) {
	s.RegisterService(&_MarketplaceTransaction_serviceDesc, srv)
}

func _MarketplaceTransaction_ListCartItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCartItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).ListCartItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/ListCartItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).ListCartItems(ctx, req.(*ListCartItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToCartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/AddToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).AddToCart(ctx, req.(*AddToCartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_UpdateCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).UpdateCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/UpdateCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).UpdateCart(ctx, req.(*UpdateCartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_RemoveCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).RemoveCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/RemoveCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).RemoveCart(ctx, req.(*RemoveCartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_ListOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).ListOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/ListOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).ListOrder(ctx, req.(*ListOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).GetOrder(ctx, req.(*GetOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/Checkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).Checkout(ctx, req.(*CheckoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_UpdateOrderStatusToOnShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).UpdateOrderStatusToOnShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/UpdateOrderStatusToOnShipment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).UpdateOrderStatusToOnShipment(ctx, req.(*ShipProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_Fulfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FulfillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).Fulfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/Fulfill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).Fulfill(ctx, req.(*FulfillReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketplaceTransaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prototransaction.MarketplaceTransaction",
	HandlerType: (*MarketplaceTransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCartItems",
			Handler:    _MarketplaceTransaction_ListCartItems_Handler,
		},
		{
			MethodName: "AddToCart",
			Handler:    _MarketplaceTransaction_AddToCart_Handler,
		},
		{
			MethodName: "UpdateCart",
			Handler:    _MarketplaceTransaction_UpdateCart_Handler,
		},
		{
			MethodName: "RemoveCart",
			Handler:    _MarketplaceTransaction_RemoveCart_Handler,
		},
		{
			MethodName: "ListOrder",
			Handler:    _MarketplaceTransaction_ListOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _MarketplaceTransaction_GetOrder_Handler,
		},
		{
			MethodName: "Checkout",
			Handler:    _MarketplaceTransaction_Checkout_Handler,
		},
		{
			MethodName: "UpdateOrderStatusToOnShipment",
			Handler:    _MarketplaceTransaction_UpdateOrderStatusToOnShipment_Handler,
		},
		{
			MethodName: "Fulfill",
			Handler:    _MarketplaceTransaction_Fulfill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
