// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package prototransaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCartItemsReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCartItemsReq) Reset()         { *m = ListCartItemsReq{} }
func (m *ListCartItemsReq) String() string { return proto.CompactTextString(m) }
func (*ListCartItemsReq) ProtoMessage()    {}
func (*ListCartItemsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *ListCartItemsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCartItemsReq.Unmarshal(m, b)
}
func (m *ListCartItemsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCartItemsReq.Marshal(b, m, deterministic)
}
func (m *ListCartItemsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCartItemsReq.Merge(m, src)
}
func (m *ListCartItemsReq) XXX_Size() int {
	return xxx_messageInfo_ListCartItemsReq.Size(m)
}
func (m *ListCartItemsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCartItemsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListCartItemsReq proto.InternalMessageInfo

func (m *ListCartItemsReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListCartItemsResp struct {
	Cart                 []*Cart  `protobuf:"bytes,1,rep,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCartItemsResp) Reset()         { *m = ListCartItemsResp{} }
func (m *ListCartItemsResp) String() string { return proto.CompactTextString(m) }
func (*ListCartItemsResp) ProtoMessage()    {}
func (*ListCartItemsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *ListCartItemsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCartItemsResp.Unmarshal(m, b)
}
func (m *ListCartItemsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCartItemsResp.Marshal(b, m, deterministic)
}
func (m *ListCartItemsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCartItemsResp.Merge(m, src)
}
func (m *ListCartItemsResp) XXX_Size() int {
	return xxx_messageInfo_ListCartItemsResp.Size(m)
}
func (m *ListCartItemsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCartItemsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListCartItemsResp proto.InternalMessageInfo

func (m *ListCartItemsResp) GetCart() []*Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type UpdateCartReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuantityKg           float64  `protobuf:"fixed64,4,opt,name=quantity_kg,json=quantityKg,proto3" json:"quantity_kg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCartReq) Reset()         { *m = UpdateCartReq{} }
func (m *UpdateCartReq) String() string { return proto.CompactTextString(m) }
func (*UpdateCartReq) ProtoMessage()    {}
func (*UpdateCartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *UpdateCartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCartReq.Unmarshal(m, b)
}
func (m *UpdateCartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCartReq.Marshal(b, m, deterministic)
}
func (m *UpdateCartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCartReq.Merge(m, src)
}
func (m *UpdateCartReq) XXX_Size() int {
	return xxx_messageInfo_UpdateCartReq.Size(m)
}
func (m *UpdateCartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCartReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCartReq proto.InternalMessageInfo

func (m *UpdateCartReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateCartReq) GetQuantityKg() float64 {
	if m != nil {
		return m.QuantityKg
	}
	return 0
}

type AddToCartReq struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuantityKg           float64  `protobuf:"fixed64,3,opt,name=quantity_kg,json=quantityKg,proto3" json:"quantity_kg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToCartReq) Reset()         { *m = AddToCartReq{} }
func (m *AddToCartReq) String() string { return proto.CompactTextString(m) }
func (*AddToCartReq) ProtoMessage()    {}
func (*AddToCartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *AddToCartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToCartReq.Unmarshal(m, b)
}
func (m *AddToCartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToCartReq.Marshal(b, m, deterministic)
}
func (m *AddToCartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToCartReq.Merge(m, src)
}
func (m *AddToCartReq) XXX_Size() int {
	return xxx_messageInfo_AddToCartReq.Size(m)
}
func (m *AddToCartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToCartReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddToCartReq proto.InternalMessageInfo

func (m *AddToCartReq) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *AddToCartReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddToCartReq) GetQuantityKg() float64 {
	if m != nil {
		return m.QuantityKg
	}
	return 0
}

type RemoveFromCartReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromCartReq) Reset()         { *m = RemoveFromCartReq{} }
func (m *RemoveFromCartReq) String() string { return proto.CompactTextString(m) }
func (*RemoveFromCartReq) ProtoMessage()    {}
func (*RemoveFromCartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *RemoveFromCartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromCartReq.Unmarshal(m, b)
}
func (m *RemoveFromCartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromCartReq.Marshal(b, m, deterministic)
}
func (m *RemoveFromCartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromCartReq.Merge(m, src)
}
func (m *RemoveFromCartReq) XXX_Size() int {
	return xxx_messageInfo_RemoveFromCartReq.Size(m)
}
func (m *RemoveFromCartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromCartReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromCartReq proto.InternalMessageInfo

func (m *RemoveFromCartReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RemoveFromCartResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromCartResp) Reset()         { *m = RemoveFromCartResp{} }
func (m *RemoveFromCartResp) String() string { return proto.CompactTextString(m) }
func (*RemoveFromCartResp) ProtoMessage()    {}
func (*RemoveFromCartResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}

func (m *RemoveFromCartResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromCartResp.Unmarshal(m, b)
}
func (m *RemoveFromCartResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromCartResp.Marshal(b, m, deterministic)
}
func (m *RemoveFromCartResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromCartResp.Merge(m, src)
}
func (m *RemoveFromCartResp) XXX_Size() int {
	return xxx_messageInfo_RemoveFromCartResp.Size(m)
}
func (m *RemoveFromCartResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromCartResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromCartResp proto.InternalMessageInfo

func (m *RemoveFromCartResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CheckoutReq struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CheckoutReq) Reset()         { *m = CheckoutReq{} }
func (m *CheckoutReq) String() string { return proto.CompactTextString(m) }
func (*CheckoutReq) ProtoMessage()    {}
func (*CheckoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{6}
}

func (m *CheckoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutReq.Unmarshal(m, b)
}
func (m *CheckoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutReq.Marshal(b, m, deterministic)
}
func (m *CheckoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutReq.Merge(m, src)
}
func (m *CheckoutReq) XXX_Size() int {
	return xxx_messageInfo_CheckoutReq.Size(m)
}
func (m *CheckoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutReq proto.InternalMessageInfo

func (m *CheckoutReq) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type CheckoutResp struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutResp) Reset()         { *m = CheckoutResp{} }
func (m *CheckoutResp) String() string { return proto.CompactTextString(m) }
func (*CheckoutResp) ProtoMessage()    {}
func (*CheckoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{7}
}

func (m *CheckoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutResp.Unmarshal(m, b)
}
func (m *CheckoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutResp.Marshal(b, m, deterministic)
}
func (m *CheckoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutResp.Merge(m, src)
}
func (m *CheckoutResp) XXX_Size() int {
	return xxx_messageInfo_CheckoutResp.Size(m)
}
func (m *CheckoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutResp proto.InternalMessageInfo

func (m *CheckoutResp) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type FulfillReq struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentAmount        int64    `protobuf:"varint,2,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FulfillReq) Reset()         { *m = FulfillReq{} }
func (m *FulfillReq) String() string { return proto.CompactTextString(m) }
func (*FulfillReq) ProtoMessage()    {}
func (*FulfillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{8}
}

func (m *FulfillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FulfillReq.Unmarshal(m, b)
}
func (m *FulfillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FulfillReq.Marshal(b, m, deterministic)
}
func (m *FulfillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FulfillReq.Merge(m, src)
}
func (m *FulfillReq) XXX_Size() int {
	return xxx_messageInfo_FulfillReq.Size(m)
}
func (m *FulfillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FulfillReq.DiscardUnknown(m)
}

var xxx_messageInfo_FulfillReq proto.InternalMessageInfo

func (m *FulfillReq) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *FulfillReq) GetPaymentAmount() int64 {
	if m != nil {
		return m.PaymentAmount
	}
	return 0
}

type FulfillResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FulfillResp) Reset()         { *m = FulfillResp{} }
func (m *FulfillResp) String() string { return proto.CompactTextString(m) }
func (*FulfillResp) ProtoMessage()    {}
func (*FulfillResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{9}
}

func (m *FulfillResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FulfillResp.Unmarshal(m, b)
}
func (m *FulfillResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FulfillResp.Marshal(b, m, deterministic)
}
func (m *FulfillResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FulfillResp.Merge(m, src)
}
func (m *FulfillResp) XXX_Size() int {
	return xxx_messageInfo_FulfillResp.Size(m)
}
func (m *FulfillResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FulfillResp.DiscardUnknown(m)
}

var xxx_messageInfo_FulfillResp proto.InternalMessageInfo

func (m *FulfillResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*ListCartItemsReq)(nil), "prototransaction.ListCartItemsReq")
	proto.RegisterType((*ListCartItemsResp)(nil), "prototransaction.ListCartItemsResp")
	proto.RegisterType((*UpdateCartReq)(nil), "prototransaction.UpdateCartReq")
	proto.RegisterType((*AddToCartReq)(nil), "prototransaction.AddToCartReq")
	proto.RegisterType((*RemoveFromCartReq)(nil), "prototransaction.RemoveFromCartReq")
	proto.RegisterType((*RemoveFromCartResp)(nil), "prototransaction.RemoveFromCartResp")
	proto.RegisterType((*CheckoutReq)(nil), "prototransaction.CheckoutReq")
	proto.RegisterType((*CheckoutResp)(nil), "prototransaction.CheckoutResp")
	proto.RegisterType((*FulfillReq)(nil), "prototransaction.FulfillReq")
	proto.RegisterType((*FulfillResp)(nil), "prototransaction.FulfillResp")
}

func init() {
	proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490)
}

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x93, 0xd2, 0xa4, 0xe3, 0x26, 0x6a, 0xe6, 0xd0, 0xa6, 0x16, 0x69, 0xa3, 0x2d, 0x88,
	0x08, 0x44, 0x0e, 0x41, 0x1c, 0x11, 0x54, 0x85, 0x42, 0x54, 0xbe, 0x64, 0x95, 0x0b, 0x12, 0x8a,
	0x16, 0xef, 0x12, 0xac, 0xc4, 0x5e, 0x67, 0x77, 0x8d, 0xd4, 0xbf, 0xce, 0xa9, 0xf2, 0x66, 0x13,
	0x27, 0x76, 0x9b, 0x9c, 0xac, 0x99, 0x79, 0x7e, 0xf3, 0xde, 0xec, 0x83, 0x96, 0x96, 0x34, 0x56,
	0x34, 0xd0, 0xa1, 0x88, 0xfb, 0x89, 0x14, 0x5a, 0xe0, 0xa1, 0xf9, 0xac, 0xf4, 0xbd, 0x46, 0x22,
	0x05, 0x4b, 0x03, 0x3d, 0x07, 0x78, 0xae, 0x90, 0x8c, 0x4b, 0x5b, 0x40, 0x40, 0xa5, 0x1d, 0x90,
	0x17, 0x70, 0xf8, 0x39, 0x54, 0xfa, 0x92, 0x4a, 0x3d, 0xd4, 0x3c, 0x52, 0x3e, 0x9f, 0xe1, 0x31,
	0xd4, 0x52, 0xc5, 0xe5, 0x28, 0x64, 0x6d, 0xa7, 0xeb, 0xf4, 0xaa, 0xfe, 0x5e, 0x56, 0x0e, 0x19,
	0x79, 0x0b, 0xad, 0x02, 0x58, 0x25, 0xf8, 0x1c, 0x76, 0x33, 0xbe, 0xb6, 0xd3, 0xad, 0xf6, 0xdc,
	0xc1, 0x51, 0xbf, 0x28, 0xa5, 0x9f, 0xc1, 0x7d, 0x83, 0x21, 0xef, 0xa0, 0xf1, 0x23, 0x61, 0x54,
	0x73, 0xd3, 0xe3, 0x33, 0x6c, 0x42, 0x65, 0xb9, 0xa5, 0x12, 0x32, 0x3c, 0x03, 0x77, 0x96, 0xd2,
	0x58, 0x87, 0xfa, 0x76, 0x34, 0x19, 0xb7, 0x77, 0xbb, 0x4e, 0xcf, 0xf1, 0x61, 0xd1, 0xba, 0x1e,
	0x93, 0x31, 0x1c, 0x5c, 0x30, 0x76, 0x23, 0x16, 0x04, 0x1d, 0x00, 0xeb, 0x34, 0x97, 0xbb, 0x6f,
	0x3b, 0x43, 0xb6, 0x6a, 0xa5, 0xb2, 0x6a, 0xa5, 0xb8, 0xa8, 0x5a, 0x5a, 0x74, 0x0e, 0x2d, 0x9f,
	0x47, 0xe2, 0x1f, 0xbf, 0x92, 0x22, 0x7a, 0x40, 0x2e, 0xe9, 0x03, 0x16, 0x41, 0x2a, 0xc1, 0x36,
	0xd4, 0x54, 0x1a, 0x04, 0x5c, 0x29, 0x03, 0xad, 0xfb, 0x8b, 0x92, 0xbc, 0x07, 0xf7, 0xf2, 0x2f,
	0x0f, 0x26, 0x22, 0x35, 0x74, 0xaf, 0xa1, 0x6e, 0xa5, 0x2a, 0x7b, 0xbe, 0x93, 0xf2, 0xf9, 0xbe,
	0xcf, 0x11, 0xfe, 0x12, 0x4a, 0xde, 0xc0, 0x41, 0xce, 0xa2, 0x12, 0x7c, 0x09, 0x8f, 0xcc, 0xf3,
	0x9a, 0x6d, 0xee, 0xe0, 0xb8, 0xcc, 0xf1, 0x2d, 0x1b, 0xfb, 0x73, 0x14, 0xf9, 0x0a, 0x70, 0x95,
	0x4e, 0xff, 0x84, 0xd3, 0x69, 0xa6, 0xe1, 0x04, 0xea, 0xa6, 0x9d, 0x9f, 0xaf, 0x66, 0xea, 0x21,
	0xc3, 0xa7, 0xd0, 0x4c, 0xe8, 0x6d, 0xc4, 0x63, 0x3d, 0xa2, 0x91, 0x48, 0x63, 0x6d, 0x6f, 0xd8,
	0xb0, 0xdd, 0x0b, 0xd3, 0x24, 0xcf, 0xc0, 0x5d, 0xf2, 0x6d, 0x72, 0x3f, 0xf8, 0x5f, 0x85, 0xa3,
	0x2f, 0x54, 0x4e, 0xb8, 0x4e, 0xa6, 0x34, 0xe0, 0x37, 0xb9, 0x40, 0xfc, 0x09, 0x8d, 0xb5, 0x64,
	0x21, 0x29, 0x9b, 0x28, 0xe6, 0xd4, 0x3b, 0xdf, 0x8a, 0x51, 0x09, 0xd9, 0xc1, 0x0f, 0xb0, 0xbf,
	0x8c, 0x0c, 0x9e, 0x96, 0xff, 0x59, 0xcd, 0x93, 0xf7, 0x40, 0x7e, 0xc9, 0x0e, 0x7e, 0x04, 0xc8,
	0xb3, 0x8b, 0x67, 0x65, 0xdc, 0x5a, 0xb2, 0x37, 0x10, 0xfd, 0x82, 0xe6, 0x7a, 0x68, 0xf0, 0x1e,
	0x23, 0xa5, 0xec, 0x79, 0x4f, 0xb6, 0x83, 0x8c, 0xdd, 0x6b, 0xa8, 0x2f, 0xd2, 0x81, 0x9d, 0x7b,
	0x44, 0xe4, 0xf9, 0xf3, 0x4e, 0x37, 0x8d, 0x0d, 0xd9, 0x27, 0xa8, 0xd9, 0xb7, 0xc5, 0xc7, 0x65,
	0x70, 0x1e, 0x23, 0xaf, 0xb3, 0x61, 0x9a, 0x31, 0xfd, 0xde, 0x33, 0xf3, 0x57, 0x77, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc1, 0xcb, 0x40, 0x1c, 0xbe, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MarketplaceTransactionClient is the client API for MarketplaceTransaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketplaceTransactionClient interface {
	ListCartItems(ctx context.Context, in *ListCartItemsReq, opts ...grpc.CallOption) (*ListCartItemsResp, error)
	AddToCart(ctx context.Context, in *AddToCartReq, opts ...grpc.CallOption) (*Cart, error)
	UpdateCart(ctx context.Context, in *UpdateCartReq, opts ...grpc.CallOption) (*Cart, error)
	RemoveFromCart(ctx context.Context, in *RemoveFromCartReq, opts ...grpc.CallOption) (*RemoveFromCartResp, error)
	Checkout(ctx context.Context, in *CheckoutReq, opts ...grpc.CallOption) (*CheckoutResp, error)
	Fulfill(ctx context.Context, in *FulfillReq, opts ...grpc.CallOption) (*FulfillResp, error)
}

type marketplaceTransactionClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketplaceTransactionClient(cc grpc.ClientConnInterface) MarketplaceTransactionClient {
	return &marketplaceTransactionClient{cc}
}

func (c *marketplaceTransactionClient) ListCartItems(ctx context.Context, in *ListCartItemsReq, opts ...grpc.CallOption) (*ListCartItemsResp, error) {
	out := new(ListCartItemsResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/ListCartItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) AddToCart(ctx context.Context, in *AddToCartReq, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/AddToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) UpdateCart(ctx context.Context, in *UpdateCartReq, opts ...grpc.CallOption) (*Cart, error) {
	out := new(Cart)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/UpdateCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) RemoveFromCart(ctx context.Context, in *RemoveFromCartReq, opts ...grpc.CallOption) (*RemoveFromCartResp, error) {
	out := new(RemoveFromCartResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/RemoveFromCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) Checkout(ctx context.Context, in *CheckoutReq, opts ...grpc.CallOption) (*CheckoutResp, error) {
	out := new(CheckoutResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/Checkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceTransactionClient) Fulfill(ctx context.Context, in *FulfillReq, opts ...grpc.CallOption) (*FulfillResp, error) {
	out := new(FulfillResp)
	err := c.cc.Invoke(ctx, "/prototransaction.MarketplaceTransaction/Fulfill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketplaceTransactionServer is the server API for MarketplaceTransaction service.
type MarketplaceTransactionServer interface {
	ListCartItems(context.Context, *ListCartItemsReq) (*ListCartItemsResp, error)
	AddToCart(context.Context, *AddToCartReq) (*Cart, error)
	UpdateCart(context.Context, *UpdateCartReq) (*Cart, error)
	RemoveFromCart(context.Context, *RemoveFromCartReq) (*RemoveFromCartResp, error)
	Checkout(context.Context, *CheckoutReq) (*CheckoutResp, error)
	Fulfill(context.Context, *FulfillReq) (*FulfillResp, error)
}

// UnimplementedMarketplaceTransactionServer can be embedded to have forward compatible implementations.
type UnimplementedMarketplaceTransactionServer struct {
}

func (*UnimplementedMarketplaceTransactionServer) ListCartItems(ctx context.Context, req *ListCartItemsReq) (*ListCartItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCartItems not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) AddToCart(ctx context.Context, req *AddToCartReq) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) UpdateCart(ctx context.Context, req *UpdateCartReq) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCart not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) RemoveFromCart(ctx context.Context, req *RemoveFromCartReq) (*RemoveFromCartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromCart not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) Checkout(ctx context.Context, req *CheckoutReq) (*CheckoutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkout not implemented")
}
func (*UnimplementedMarketplaceTransactionServer) Fulfill(ctx context.Context, req *FulfillReq) (*FulfillResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fulfill not implemented")
}

func RegisterMarketplaceTransactionServer(s *grpc.Server, srv MarketplaceTransactionServer) {
	s.RegisterService(&_MarketplaceTransaction_serviceDesc, srv)
}

func _MarketplaceTransaction_ListCartItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCartItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).ListCartItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/ListCartItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).ListCartItems(ctx, req.(*ListCartItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToCartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/AddToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).AddToCart(ctx, req.(*AddToCartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_UpdateCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).UpdateCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/UpdateCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).UpdateCart(ctx, req.(*UpdateCartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_RemoveFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromCartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).RemoveFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/RemoveFromCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).RemoveFromCart(ctx, req.(*RemoveFromCartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/Checkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).Checkout(ctx, req.(*CheckoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceTransaction_Fulfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FulfillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceTransactionServer).Fulfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prototransaction.MarketplaceTransaction/Fulfill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceTransactionServer).Fulfill(ctx, req.(*FulfillReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketplaceTransaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prototransaction.MarketplaceTransaction",
	HandlerType: (*MarketplaceTransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCartItems",
			Handler:    _MarketplaceTransaction_ListCartItems_Handler,
		},
		{
			MethodName: "AddToCart",
			Handler:    _MarketplaceTransaction_AddToCart_Handler,
		},
		{
			MethodName: "UpdateCart",
			Handler:    _MarketplaceTransaction_UpdateCart_Handler,
		},
		{
			MethodName: "RemoveFromCart",
			Handler:    _MarketplaceTransaction_RemoveFromCart_Handler,
		},
		{
			MethodName: "Checkout",
			Handler:    _MarketplaceTransaction_Checkout_Handler,
		},
		{
			MethodName: "Fulfill",
			Handler:    _MarketplaceTransaction_Fulfill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
